### ISSUE TITLE
plugin_extfile chooses wrong IP on geoip resources

### ISSUE THREAD

**Issue by kupson** [gdnsd/gdnsd#100]
Hi,

Gdns starts without "/var/tmp/ext1data" file and then I'm marking one of the IPs as down:

    echo "192.0.2.2 => DOWN/60" > /var/tmp/ext1data

Logs:

    2015-08-05_11:30:22.06838 # warning: plugin_extfile: Service type 'ext1': '192.0.2.2' was defaulted! (not specified by input file)
    2015-08-05_11:30:22.06848 # warning: plugin_extfile: Service type 'ext1': '192.0.2.3' was defaulted! (not specified by input file)
    2015-08-05_11:30:22.06850 # info: state of '192.0.2.1/ext1' changed from UP/MAX to DOWN/60 

Somehow the 192.0.2.1 is set to DOWN state.

Below are fragments of config file to reproduce the problem:

    service_types => {
        ext1 => {
            plugin => "extfile",
            file => "/var/tmp/ext1data",
            direct => true,
            def_down => false,
            def_ttl => 600,
        }
    }
    plugins => {
        geoip => {
            maps => {
                testmap => {
                    geoip_db => GeoIPCityv6.dat
                    geoip_db_v4_overlay => GeoIPCity.dat
                    datacenters => [ dca, dcb, dcc ]
                    map => {
                        default => [ dca ]
                        EU  => {
                            default => [ dcb ]
                        }
                        NA => {
                            default => [ dcc ]
                        }
                    }
                }
            }
            resources => {
                grr1 => {
                    map => testmap
                    multi => true
                    plugin => weighted
                    service_types => ext1
                    up_thresh => 0.3
                    dcmap => {
                        dca => {
                            testrr-2 => [ 192.0.2.2, 100 ]
                            testrr-1 => [ 192.0.2.1, 100 ]
                        }
                        dcb => {
                            testrr-3 => [ 192.0.2.3, 100 ]
                        }
                        dcc => {
                            testrr-3 => [ 192.0.2.3, 100 ]
                        }
                    }
                }
            }
        }
    }

Good IP address is picked on weighted (non-geoip) resources.

Kind Regards,
Rafal

**Comment by blblack** [comment]
Hey - thanks for the report and a working example!  This is a real bug, and it's related to internal sorting of the addresses added to the extfile service_type.  As a temporary workaround, I suspect you can fix this by re-ordering your `testrr-1` and `testrr-2` lines in the example config (so that config order matches natural sort order of the address data).

**Comment by blblack** [comment]
The fix is released in 2.1.3 and 2.2.1
