### ISSUE TITLE
Access-Control-Allow-Origin Header on Machine Readable Output

### ISSUE THREAD

**Issue by Muny-** [gdnsd/gdnsd#101]
I think an option for adding a configurable `Access-Control-Allow-Origin` header to the machine readable http status pages would be very useful for monitoring systems which require browsers to grab those URLs.  I'd rather grab the page directly in browser as opposed to grabbing it by proxy from a local script.

As it is currently, if a browser attempts to access the status URLs, they throw this error:
![Screenshot](https://pcbx.us/muny/butl.png)

**Comment by blblack** [comment]
In the long run (targeting 3.x release), we're dropping the internal HTTP server completely in favor of outputting data over control socks and to filesystem paths for a real webserver (e.g. local nginx/apache/lighttpd) to serve, along with some sample static HTML+javascript for a simple browser UI that dynamically reloads the data source.  If someone wants to do a pull req to implement this for 2.x in the interim, we could do so, but I'd consider it pretty low priority at this point.

**Comment by blblack** [comment]
Internal HTTP server is gone for 3.0.
