### ISSUE TITLE
v4-only zone

### ISSUE THREAD

**Issue by fascinatedcow** [gdnsd/gdnsd#104]
Hi there,

I'd like to reuse a geoip map in two different zones, one that hands out v6 and one that hands out v4. At present I can't see a way to do this without duplicating the whole map.

I looked at ADDR_LIMIT_V4, but setting this to 0 means infinity rather than actually 0 so that's no use.

Is this possible at all?

Many thanks,

Matt

**Comment by blblack** [comment]
In the geoip plugin config, a "map" is separate from a resource, and can be re-used by multiple resources.  You could share a map between separate v4 and v6 address resources.

**Comment by fascinatedcow** [comment]
Thanks for the response. That sounds like what I want to do. Are you able to advise how to do it?

**Comment by blblack** [comment]
It's in the docs.  Looking at the example syntax in https://github.com/gdnsd/gdnsd/wiki/GdnsdPluginGeoip , you can see the separate sub-stanzas for "maps" and "resources".  Resources refer to a map by name.  Simply define a resource with only v4 addresses, and another for only v6 addresses, and have them both name the same map.
