### ISSUE TITLE
Support for geonames.org

### ISSUE THREAD

**Issue by extremeshok** [gdnsd/gdnsd#114]
Currently gdnsd appears to only support the maxmind geoip databases.

It would be possible to add support for the free GeoNames Gazetteer data  ?

Databases ( http://download.geonames.org/export/dump/ )

About  ( http://www.geonames.org/about.html )

**Comment by blblack** [comment]
I don't think GeoNames has an IP address data.  Was there some specific way you wanted to use the data the do have with the geoip plugin?

**Comment by extremeshok** [comment]
They dont have ip data, but they allow reverse geocoding, finding places through postal codes, finding places next to a given place, etc.

So it would complement the current databases

**Comment by blblack** [comment]
I can see how we can hook that up, but I question the utility of it tbh.  Ultimately the GeoIP database only has the data that it does have, and adding another index into that information isn't going to make responses more-specific.  If we mapped geonames postal codes into the config, they would just have to be remapped to countries (or state/province, or city) first anyways.

Also, usually geodns's level of accuracy isn't high enough that things like individual postal codes have clear utility.  Usually, anything deeper than the Country (or State/Province, for very large countries) level is going to be pretty fuzzy.  We do currently allow mapping down to the City level, but honestly breaking things down by-city is unlikely to be useful in practice in very many real-world situations for geodns purposes.

The gist of the accuracy issues referenced above are (a) almost all users are coming through DNS caches, most of which don't send edns-client-subnet data, and some of those caches are quite distant from the real users, combined with (b) even if the geodns lookup gave perfect location information on the end-user, geographic distance is only a fuzzy proxy at best for network distance in latency terms.
