### ISSUE TITLE
Zone template inconsistencies

### ISSUE THREAD

**Issue by extremeshok** [gdnsd/gdnsd#116]
Which format/template does one follow for the zone NS records.

some of my zones will have ttl for the ns others will not

According to https://git.wikimedia.org/blob/operations%2Fdns.git/master/templates%2Fwikidata.org

````
; Name servers
 
            1D  IN NS   ns0.wikimedia.org.
            1D  IN NS   ns1.wikimedia.org.
            1D  IN NS   ns2.wikimedia.org.
 ````

But accoridng to https://github.com/gdnsd/gdnsd/wiki/GdnsdZonefile
````
  @     NS      ns1.example.com.
  @     NS      ns2
  @     NS      ns.example.net.
````

Thanks

**Comment by extremeshok** [comment]
Same issue with MX records

According to https://git.wikimedia.org/blob/operations%2Fdns.git/master/templates%2Fwikidata.org
````
;Mail exchangers
 
            1H  IN MX   10  mx1001.wikimedia.org.
            1H  IN MX   50  mx2001.wikimedia.org.
````
But accoridng to https://github.com/gdnsd/gdnsd/wiki/GdnsdZonefile
````
  @     7200    MX      10 mail-a
  @     7200    MX      100 mail-b
````

**Comment by extremeshok** [comment]
Please advise

**Comment by blblack** [comment]
These are not inconsistencies.  The basic syntax of traditional zonefiles is documented in [RFC 1035](http://www.rfc-editor.org/rfc/rfc1035.txt), as mentioned at [GdnsdZonefile#description](https://github.com/gdnsd/gdnsd/wiki/GdnsdZonefile#description) .  The RFC allows a lot of flexibility in the format, and can be difficult to understand, but both the examples in the documentation and the linked zonefiles for wikidata.org are legal and correct.

To summarize from the RFC:

* Resource record lines come in two forms:
```
    <domain-name><rr> [<comment>]
    <blank><rr> [<comment>]
```

* The `<rr>` part above also comes in two forms, which basically allow either ordering of the first two fields, both of which are entirely optional.  The only thing that prevents confusion here is that there is no alias between any legal <class> and <TTL> values:
```
    [<TTL>] [<class>] <type> <RDATA>
    [<class>] [<TTL>] <type> <RDATA>
```

* If the `<domain-name>` part is blank, the most-recently used named above (e.g. from a previous RR)  is re-used.  At the start of the zonefile, when there is no previous name, a blank name is equivalent to the name of the zone itself.  Anywhere else, the special sigil `@` can be used in place of the zone's name.

* If the `<class>` is missing, it defaults to `IN` for Internet, which is the only pragmatically-useful class name anyways.

* If the `<TTL>` is missing, the original RFC 1035 stated that it would be defaulted to the last explicit TTL mentioned in the file (whatever record was above, presumably), but that wasn't a great idea.  RFC 2308 added `$TTL` to set a default TTL value to use when an RR doesn't specify it.  gdnsd goes one further and defines a global default TTL in the config file, which applies at the start of all zonefiles until they declare their own local `$TTL`.

* Given all of the above, in a zonefile for `example.com`, if the first line is `$TTL 3600`, all of the following 15 examples would have identical meaning if used as the second line of that zonefile:

```
example.com. 3600 IN NS ns1
example.com. IN 3600 NS ns1
example.com. IN NS ns1
example.com. 3600 NS ns1
example.com. NS ns1
@ 3600 IN NS ns1
@ IN 3600 NS ns1
@ IN NS ns1
@ 3600 NS ns1
@ NS ns1
  3600 IN NS ns1
  IN 3600 NS ns1
  IN NS ns1
  3600 NS ns1
  NS ns1

**Comment by extremeshok** [comment]
@blblack thanks for your informative reply.
