### ISSUE TITLE
Assigning template variables {{ zonename }} {{ serial }}

### ISSUE THREAD

**Issue by extremeshok** [gdnsd/gdnsd#117]
How can I use a variable in the template file to set the zonename to the name of the template file.

And set the serial to automatically use the mtime of the template file.

According to https://git.wikimedia.org/blob/operations%2Fdns.git/master/templates%2F59.15.185.in-addr.arpa
````
$ORIGIN {{ zonename }}.
@       1D IN SOA  ns0.wikimedia.org.       hostmaster.wikimedia.org.        (
                                        {{ serial }}    ; serial
                                        12H             ; refresh
                                        2H              ; retry
                                        2W              ; expiry
                                        1H              ; negative cache TTL
                                        )
````

I tried using the following with version 2.1.2, which results in a "general parse error"

I am assuming your using puppet/chef/ansible to set the values and not dynamically via gdnsd

Thanks

**Comment by blblack** [comment]
Right, gdnsd doesn't have any built-in templating.  Those templates you're looking at in Wikimedia's respositories are processed by an external templating and deployment script (which isn't driven by puppet/chef/ansible, but you certainly can do such a thing).
