### ISSUE TITLE
fyi: PowerDNS to gdnsd domain/zone Migrator

### ISSUE THREAD

**Issue by extremeshok** [gdnsd/gdnsd#119]
This will be of interest and use to your users: https://github.com/extremeshok/powerdns-to-gdnsd

Please feel free to add it to your wiki, etc

The following was developed to migrate a 5node powerdns mysql cluster with over 2000 domains to gdnsd. The script can also be run via cron, this could allow you to still use your the current powerdns database and webinterfaces to generate working gdnsd records, without actually using powerdns. Please see the "sample" directory or the travis-ci build logs to see 2 examples of generated records.

**Comment by extremeshok** [comment]
ping

**Comment by blblack** [comment]
Not a (code) bug.  It's nice to know that's out there, but at least for me it would seem a little confrontational to links a PowerDNS->gdnsd convertor from gdnsd's page (especially as gdnsd lacks many of PowerDNS's features and doesn't really directly compete with it for general-purpose use).
