### ISSUE TITLE
implement dynamic re-balancing based on capacity for geoip automatic mapping

### ISSUE THREAD

**Issue by vedranf** [gdnsd/gdnsd#126]
Hello,

I couldn't find anything in the docs about it so this could be considered as a wishlist, although it might be already supported, even though it's not directly obvious to me.

I have several datacenters and use auto_dc_coords/city-auto-mode and when one of them is marked as down, client is then directed to the next closest datacenter which is ok in most cases. However, in my case, I'm using gdnsd not only for selecting the closest DC but for load-balancing between them. That means, in a rare even when whole DC goes down, some other DC will get all of its traffic, potentially more than doubling the load on its servers and perhaps overloading it and thus triggering a chain reaction. What would I like to do in an event of DC failing to respond to checks, is to return all or a custom list of DCs/addresses. For example, if there are 4 DCs: a, b, c and d; if a goes down, return b,c,d; if b goes for return c and d; etc.
Point being here is to spread this extra load across multiple other DCs (even if they aren't closest to client) rather than triggering a potential chain reaction by consecutively overloading remaining DCs one by one.
Currently, I made a static override map for some (large) countries, e.g.

map => { EU => { FR => [dc1, all_but_dc1], ... } }

where "all_but_dc1" pseudo-DC contains the list of IP addresses of all DCs expect for the failed DC1 and this should work if I got it right, but it would be easier to have something like this supported out of the box, without doing manual, per-country, hacks. Please let me know if something like this is already possible.

Thanks,
Vedran

**Comment by blblack** [comment]
Nothing like that exists yet, and for the moment what you're doing (manually defining the map such that the next DC after DC1 is different for various countries that are primary to DC1) is the best approach.

This is a known wishlist item, but not tracked here in gdnsd's issue tracker.  I put down some (probably wrong!) thoughts on fixing it in a Wikimedia phabricator ticket here a while back: https://phabricator.wikimedia.org/T94697 .  I'm going to edit the title of this ticket too, so it can track this feature here.

**Comment by blblack** [comment]
Reflecting on the title update a bit without going into the detail level of the above-linked phab ticket: the idea here is that the geoip plugin needs some additional input metadata representing the load-capacity of each datacenter and some notion of the load value of various regions of the world, and then make use of this in auto-generated mapping to make better decisions in all possible datacenter up/down state combinations.

For example, when a higher-capacity datacenter fails, its clients may need to be redistributed to multiple nearby lower-capacity datacenters intelligently, and in response to this increased load some of the previous clients of those lower-capacity datacenters may need to shift other DCs as well, etc.  So basically you're load-rebalancing the world dynamically as appropriate.

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
