### ISSUE TITLE
FYI: systemd 231 now listens on 127.0.0.53:53

### ISSUE THREAD

**Issue by chabu-jp** [gdnsd/gdnsd#128]
It's natural, gdnsd fails to start without a `listen` option.

```
Jul 31 12:14:20 AQUA gdnsd[507]: Failed to bind() TCP DNS socket to 0.0.0.0:53
Jul 31 12:14:20 AQUA gdnsd[510]: Loading configuration from '/usr/local/etc/gdnsd/config'
Jul 31 12:14:20 AQUA gdnsd[510]: Did not find a running daemon to stop!
Jul 31 12:14:20 AQUA systemd[1]: Failed to start gdnsd.
```

```
# ss -ln
Netid  State      Recv-Q  Send-Q  Local Address:Port  Peer Address:Port
udp    UNCONN     0       0       127.0.0.53%lo:53    *:*
tcp    LISTEN     0       128     127.0.0.53%lo:53    *:*
```

> CHANGES WITH 231:
> ...
> * systemd-resolved now listens on the local IP address 127.0.0.53:53
>   for DNS requests. ...
> ...

https://github.com/systemd/systemd/blob/master/NEWS

**Comment by blblack** [comment]
Yeah that's going to make things tricky for a default config that works out of the box :/

We could go back towards some kind of interface-scanning, but that was always buggy without going fully-dynamic and receiving trigger events on interface changes (and messy for portability and thread creation, etc).  I've been trying to move away from interface scanning, and other than this it's the superior approach.

Of course, users of gdnsd will likely want to bind it to a particular set of public `listen` addresses anyways, but not having a default config that starts up at all (at least, in the absence of a concurrent recdns server on the same host!) is annoying...

**Comment by chabu-jp** [comment]
After testing with my Arch, I will close this issue. Thanks!

> CHANGES WITH 232:
> ...
> \* systemd-resolved gained a new "DNSStubListener" setting in
>   resolved.conf. It either takes a boolean value or the special values
>   "udp" and "tcp", and configures whether to enable the stub DNS
>   listener on 127.0.0.53:53.
> ...

https://github.com/systemd/systemd/blob/master/NEWS (2016-11-03)

I found similar discussions. But they are exceeded my English skills...
- https://github.com/systemd/systemd/pull/4061 (2016-08-30)
- https://github.com/PowerDNS/pdns/issues/4505 (2016-09-25)
