### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by alter** [gdnsd/gdnsd#129]
Hi,
Do you plan to make http rest api for working with gdnsd ?
For example, a lot of companies have automated systems which works with AWS/GCE/Azure/etc clouds' API and their systems could automatically create new instance, setup system, puppet/chef/ansible/etc and if they use gdnsd they obviously need in something like an API for adding new hosts into zones and pools automatically via deploy system.

**Comment by blblack** [comment]
I'm guessing you mean a REST API for manipulating zone data (defining A/AAAA/PTR for dynamic host instance creations).  I doubt that's in the cards anytime in the near future.  There's a lot of design issues wrapped up in that idea in general.  gdnsd doesn't own the data, it serves the data over the DNS protocol.  From a sort of unix philosophical stance, updating the data gdnsd serves belongs in a separate component (either that or we have to define how updates happen bi-directionally and sanely for all current and future backends).

In theory, a given zone data backend can be dynamic.  They already are for the existing file-based data backends, when the files are updated.  However, the auto-reload work has left us in a state where it's best to not support `$INCLUDE`, which in turn makes templating dynamic data into static files more painful than it should be...
