### ISSUE TITLE
First closest "N" servers/datacenters (in distance order) - is this possible with existing plugins?

### ISSUE THREAD

**Issue by ghub2015** [gdnsd/gdnsd#130]
Hi, I recently started testing gdnsd and it is definitely an interesting implementation; kudos on what you done so far.

Is this scenario possible with the existing plugins?
- Return the first closest  "N"  IPs; in distance order, from closest to furthest away; _without any round-robin shuffling?_
- So, for example, if you have 3 datacenters, with dcA being the closest for a particular query, then dcB further away, and dcC farthest away, and you just want 2 RR's returned (closest 2 datacenters), queries would return:

dcA  10 IN  A x.x.x.x
dcB  10 IN  A y.y.y.y

The closest I have gotten is to use "geoip" with multiple IP's for the datacenters:
dcA => [x.x.x.x, y.y.y.y]
dcB => [y.y.y.y, x.x.x.x]
dcC => [z.z.z.z, y.y.y.y]

But, this:
- does round-robin shuffling of the result set
- has no regard for distance beyond one of the IP's returned (and is subject to round-robin shuffling)
- cannot dynamically return "N" ips (would have to modify config and force-reload)

Thanks in advance.

**Comment by blblack** [comment]
I don't think the current geoip plugin can do that, no.  Keep in mind that you can't really trust or rely on ordering within the records of an RRset to begin with.  Even if we make gdnsd (the authserver) return them in a consistent order, caches aren't required to honor that order, and neither are client libraries and such.  The norm is that they have an incentive to shuffle or sort them, if anything.

**Comment by ghub2015** [comment]
Thanks for your reply Brandon (I didn't realize you had replied).

I've been testing heavily for a month or so, across approx 20+ nameservers and it seems to hold up well.

I know you get a lot requests and I respect the time/effort to maintain this, so first I will say thank you for this.

I'll just mention some "could be nice" features that I know you have probably heard (or are even posted here already):
- More logging (so that, for example fail2ban could be utilized to ratelimit/throttle potential attacks)
- HTTPS/authentication on the status page
- Email notification (with Up/Down/Change of State options) for monitored resources
- AXFR (to play "nice" with external hosts as secondaries; yes I know it will be unknown how some of the geoDNS records would play out)
- A basic API (could then do things like Dynamic DNS, or dns-01 validation for LetsEncrypt certificates, etc)

In any case, thanks again and I find a way to contribute to the effort, I will.

Cheers

**Comment by MartinNowak** [comment]
> does round-robin shuffling of the result set

FWIW gdnsd itself doesn't shuffle, it's intermediate resolvers that do, e.g. notoriously your local dnsmasq but also Google's DNS. Try e.g. `dig amazon.de @8.8.8.8`.

> has no regard for distance beyond one of the IP's returned (and is subject to round-robin shuffling)

Right, distance is measured to datacenter, not to server IPs.

<hr></hr>

Initially I also thought this would be nice to spread 3 servers geographically, while also use them as failover servers. This doesn't seem possible with the current state of DNS, as random/shuffled servers meant some clients connected to a distant server during normal operation. And while priority is available for MX records, it's not for A and AAAA records.

So no good client-side DNS failover/browser-retry.

What you can do:
- Either add failover servers per datacenter, then deliver all addresses of the closest datacenter.
- Use a short TTL and rely on gdnsd's datacenter failover when the closest goes down.
  This incurs a short interuption until explicit client retry (e.g. F5 refresh) AFAIU, but can still failover within e.g. 10s. On the downside this also means more DNS traffic and higher resolve latency for clients, as short TTLs prevent caching.
