### ISSUE TITLE
Make gdnsd not require ragel for normal builds

### ISSUE THREAD

**Issue by zi0r** [gdnsd/gdnsd#133]
It adds around eleventy-billion dependencies.  Perhaps the files it generates can be included in the tarball instead?

**Comment by allanjude** [comment]
+1

**Comment by blblack** [comment]
It was that way in the past, where the ragel outputs were stored into the tarball.  The counter-arguments are: it's better to have git clones and tarballs be as close as possible, to not inflate the tarball size with generated outputs, and that really most people shouldn't be building the package routinely (they should be building a package once for their org, or using a distro package).  ragel is pretty widely available, it doesn't seem like much trouble to install it from a standard distro package alongside all the other compilation tools...

**Comment by zi0r** [comment]
I maintain the port (and resulting package) for gdnsd under FreeBSD: [https://www.freshports.org/dns/gdnsd2](https://www.freshports.org/dns/gdnsd2)

For FreeBSD users that choose to install software via ports (as opposed to the packages), this results in bringing ragel+all of its dependencies in for the build--which adds a decent delay to the build time as well as the additional dependencies.

Perhaps it would make sense to include the ragel outputs and have a Makefile define or configure argument that can trigger the use of embedded copies or actively regenerate them?  Most people likely won't have a need/desire to regenerate them.  It isn't rare to see a 'release' target in the Makefile that builds/embeds ragel-like output in the tarball.

I had opened the ticket after the version bump to 2.x and realizing the build dependency sprawl.

Am hoping you will reconsider.

**Comment by allanjude** [comment]
Thank you

**Comment by zi0r** [comment]
<3

**Comment by zi0r** [comment]
I believe we need a change to configure to enable a --without-ragel or the like.  It looks like it still tries to find/use it by default.

**Comment by blblack** [comment]
@zi0r - The change that put the ragel outputs back in the tarball is only in the 2.99.x beta series of releases.  The configure script there doesn't look for ragel at all, and the Makefile.am blindly assumes the program "ragel" from $PATH will work, but should only execute it if the timestamp of the ragel source files are newer than the C outputs shipped in the tarball.  Maybe a timestamp problem (or a build process that intentionally uses tar's `-m` flag to reset all the timestamps)?  Do we need the configure arg just to avoid the attempted execution if the timestamps come out wrong?

**Comment by zi0r** [comment]
Ah, I was reviewing the wrong branch then--sorry for the confusion.

If it's trivial, it might be beneficial to have a flag to conditionally avoid attempting to execute.  From a package build perspective, we sometimes run into scenarios where a user might have something (ragel) installed for another reason.  If the port conditionally does things based on what is there/not there (and we can't tie it to a configure knob), then we can sometimes end up with unexpected results.

With the FreeBSD ports tree, we try to explicitly set --with-foo or --without-foo (or whatever the knob is) based on whether or not an option is enabled.  This helps ensure that configure doesn't automagically find something in some environments and just use it.
