### ISSUE TITLE
I want to do NOT a gdmaps.c file notify check like this zones_rfc1035_auto => false

### ISSUE THREAD

**Issue by dincerkurnaz** [gdnsd/gdnsd#135]

**Comment by blblack** [comment]
This is ancient, but I'd be interesting to understand the rationale.  In general, I think we'll move this way eventually anyways (as we've done with zonefiles most-recently), but it doesn't seem to be so much of a pragmatic issue with GeoIP database updates.

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
