### ISSUE TITLE
Add the CAA RR type (RFC 6844)

### ISSUE THREAD

**Issue by paravoid** [gdnsd/gdnsd#138]
Quoting from the RFC:
>The Certification Authority Authorization (CAA) DNS Resource Record allows a DNS domain name holder to specify one or more Certification Authorities (CAs) authorized to issue certificates for that domain.  CAA Resource Records allow a public Certification Authority to implement additional controls to reduce the risk of unintended certificate mis-issue.

Example record:
```
   $ORIGIN example.com
   .       CAA 0 issue "ca.example.net"
   .       CAA 0 iodef "mailto:security@example.com"
   .       CAA 0 iodef "http://iodef.example.com/"
```

I suppose this may be not so easy to implement until #96 gets fixed.

**Comment by sunnybear** [comment]
TYPE237 doesn't work :(
TYPE257 \# 27 31323820697373756520226C657473656E63727970742E6F726722
results in

# dig webogroup.com CAA
;; Got bad packet: FORMERR
81 bytes
00 fd 85 00 00 01 00 01 00 00 00 01 09 77 65 62          .............web
6f 67 72 6f 75 70 03 63 6f 6d 00 01 01 00 01 c0          ogroup.com......
0c 01 01 00 01 00 00 00 b4 00 1b 31 32 38 20 69          ...........128.i
73 73 75 65 20 22 6c 65 74 73 65 6e 63 72 79 70          ssue."letsencryp
74 2e 6f 72 67 22 00 00 29 04 00 00 00 00 00 00          t.org"..).......
00                                                       .

**Comment by sunnybear** [comment]
sorry, my fault. It works. But who knows how?

**Comment by extremeshok** [comment]
+1 Urgently need CAA records as this is now mandated, https://blog.qualys.com/ssllabs/2017/03/13/caa-mandated-by-cabrowser-forum
````
Certification Authority Authorization (CAA), specified in RFC 6844 in 2013, is a proposal to improve the strength of the PKI ecosystem with a new control to restrict which CAs can issue certificates for a particular domain name. Although CAA had been in the proposed-standard state for more than 4 years, there was little obvious happening until very recently, with only a hundred or two hundred sites adopting it. But that’s going to change, because the CA/Browser Forum recently voted to mandate CAA support as part of its certificate issuance standard Baseline Requirements. The changes will become effective in September 2017.
````
'

**Comment by extremeshok** [comment]
The following does NOT work
Standard` BIND Zone File
For BIND ≥9.9.6, PowerDNS ≥4.0.0, NSD ≥4.0.1, Knot DNS ≥2.2.0
``
apollo-auto.com.	IN	CAA	0 issue "comodoca.com"
apollo-auto.com.	IN	CAA	0 issue "letsencrypt.org"
apollo-auto.com.	IN	CAA	0 issue "symantec.com"
apollo-auto.com.	IN	CAA	0 issuewild ";"
apollo-auto.com.	IN	CAA	0 iodef "mailto:spam@mailshok.com"
``

This does work
Legacy Zone File (RFC 3597 Syntax)
For BIND <9.9.6, NSD <4.0.1
``
apollo-auto.com.	IN	TYPE257	\# 19 00056973737565636F6D6F646F63612E636F6D
apollo-auto.com.	IN	TYPE257	\# 22 000569737375656C657473656E63727970742E6F7267
apollo-auto.com.	IN	TYPE257	\# 19 0005697373756573796D616E7465632E636F6D
apollo-auto.com.	IN	TYPE257	\# 12 0009697373756577696C643B
apollo-auto.com.	IN	TYPE257	\# 31 0005696F6465666D61696C746F3A7370616D406D61696C73686F6B2E636F6D
``

**Comment by extremeshok** [comment]
Any updates on this ?
