### ISSUE TITLE
Support for RFC2136 aka Dynamic DNS Update

### ISSUE THREAD

**Issue by extremeshok** [gdnsd/gdnsd#140]
RFC2136-style updates are supported in ISC BIND, and since version 4.0 also in PowerDNS authoritative server.

This allows for signed (or unsigned) updates to happen on your DNS zones over the network

https://www.ietf.org/rfc/rfc2136.txt

**Comment by blblack** [comment]
This really doesn't fit gdnsd's model and intended operation, sorry.  It's not a general-purpose authserver with every bell and whistle for every use-case.  None of the current zone data backends are intended to take on dynamic updates in this way.
