### ISSUE TITLE
gdnsd log file

### ISSUE THREAD

**Issue by lastsky** [gdnsd/gdnsd#142]
it there any chances to define a separate log file via config?

found but not helps - 

~~~
 -x - No syslog output (must use -f with this if [re]start)
~~~

**Comment by blblack** [comment]
No separate logfile exists in current versions or future plans.  Logs can be emitted to syslog or to stderr, everything else is out-of-scope (managing logfiles properly is tricky, and it's non-core complexity we'd rather avoid).
