### ISSUE TITLE
Correct way to override service_type, etc. when using fallback CNAMEs

### ISSUE THREAD

**Issue by zi0r** [gdnsd/gdnsd#148]
The documentation says you can do this:

`
dcmap => {
service_types => my_test,
dc-foo => { things => 1.2.3.4 },
dc-bk => fallback.static.cname.example.com.`

to specify a fallback CNAME entry, however, it does not appear possible to override previously defined service_types in the fallback CNAME case.  In my case, I was forced to define the entry for the fallback CNAME above the dcmap and then override the individual dc-foo entries with my desired service_types there to set a service_types for dc-bk.

I'd like to be able to 

`
dcmap =>
service_types => my_test,
dc-foo => { things => 1.2.3.4 },
dc-bk => { service_types => up, fallback.static.cname.example.com.`

or something similar.

**Comment by blblack** [comment]
Not sure what to do with this yet, but keeping it open to remember about this issue when reworking all related things in the future.

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
