### ISSUE TITLE
How to reload plugin and service

### ISSUE THREAD

**Issue by dgben2015** [gdnsd/gdnsd#152]
Hello,
I want to write a Web panel for services domain  resolve .
And gdnsd has  zones_rfc1035_auto can auto reload zone files.
But do not any conf for reload the plugin and service config files.

Now,I cron job “service gdnsd restart" for reload plugin and service config files.
But that have problem : make NS unable to provide stable services.

May I have any conf or other function to reload plugin and service config files ?

Thanks!

**Comment by dgben2015** [comment]
I know a domain name can has 2~4 or more NS server config.
That In practice, it does not affect the use of.
But I want to find more elegant function for reload plugin and service .

**Comment by vitclone** [comment]
You can use command `gdnsd restart` for almost seamless overlapped restart, but this feature is conflicting with systemd unit. Actually this issue duplicates [#132](https://github.com/gdnsd/gdnsd/issues/132).

**Comment by dgben2015** [comment]
Thanks!
I close this issues.
