### ISSUE TITLE
Return all IP when more than 50% monitored nodes are down ?????

### ISSUE THREAD

**Issue by bashsiz** [gdnsd/gdnsd#153]
Hi 
I have a problem with this service .
In my test the config files are like the following 

this is my service type config 

`service_types => {`
 `       sshcheck => {`
 `               plugin => tcp_connect,`
 `               port => 3022,`
 `               up_thresh => 1,`
 `               ok_thresh => 1,`
 `               down_thresh => 1,`
 `               interval => 2,`
 `               timeout => 1`
 `       },`
`}`

`plugins => {`
`        null => {}`
`        geoip => {`
`                maps => {`
`                        IR => {`
`                                nets => dcir ,`
`                                datacenters => [ dc_tehran , dc_tabriz ]`
`                        }`
`                }`
`resources => {`
`                       test => {`
`                               map =>  IR ,`
`                               service_types => [sshcheck] ,`
`                               dcmap => {`
`                                       dc_tehran => [ 192.168.5.11 , 192.168.5.12 , 192.168.5.13 , 192.168.5.14 , 192.168.5.15 , 192.168.5.16 , 192.168.5.17 , 192.168.5.18 , 192.168.5.19 , 192.168.5.20 , 192.168.5.21 , 192.168.5.22 , ],`
`                                        dc_tabriz => { service_types => [sshcheck] , lb01 => 192.168.5.101 }`
`                                }`
`                       }`
`}`

my dcir file 

`192.168.6.10/32 => dc_tabriz`
`192.168.5.0/24 => dc_tehran`

my zone file 

`$TTL 86400`
`@   IN  SOA    gdns-01.test.voip. admin.test.voip. (`
`        2011071001  ;Serial`
`        3600        ;Refresh`
`        1800        ;Retry`
`        604800      ;Expire`
`        86400       ;Minimum TTL`
`)`
`@               IN      NS      gdns-01.test.voip.`
`@               IN      NS      gdns-02.test.voip.`
`@               IN      A       192.168.5.21`
`gdns-01           IN      A       192.168.5.21`
`gdns-02           IN      A       192.168.5.22`
`test                                                            600     DYNA    geoip!test`

when all nodes are UP the dig result is all ip addresses 
when 192.168.5.11 changes from UP to DOWN dig result does not contain 192.168.5.11
every thing is OKEY until the down nodes are more than 50% of all nodes .
for example when there is 3 nodes in one DC if one of them is down service works FINE but when 2 of 3 nodes are down it returns ALL DNS RECORDS .

I CAN NOT UNDERSTAND WHAT THE PROBLEM IS ???
HOW CAN I SOLVE THIS PROBLEM ???
pls help me .

**Comment by vitclone** [comment]
Look for the up_thresh in [Multifo ](https://github.com/gdnsd/gdnsd/wiki/GdnsdPluginMultifo)plugin documentation. Default value is 0.5, this is exactly your case.
Also you can read [Metafo ](https://github.com/gdnsd/gdnsd/wiki/GdnsdPluginMetafo)plugin documentation for understand Geoip plugin better, especially why Multifo plugin used for array of IPs.

**Comment by bashsiz** [comment]
Hi dear vitclone
Thank you very much
This is exactly what i want . It was my mistake .
Thank you again .
