### ISSUE TITLE
Allow multifo plugin to return all IP addresses in pool regardless of availability of individual endpoints

### ISSUE THREAD

**Issue by andrewheberle** [gdnsd/gdnsd#154]
We have a use case where we have two datacenters which we use a combination of geoip and multifo plugins so that a pool of IP addresses are returned that is closest to the user.

Ideally we want to return all IP addresses in the multifo pool regardless of the availability of the individual endpoints, however if all endpoints are down in a DC we want to fail over to the other DC.

The need for this comes from the particular application that does it's own DNS based fail-over (ie not simple round-robin DNS) whereby when given multiple A records in a response the application chooses one of the IPs for it's persistent connection to the service.  In the event of a failure the application uses tries the next available IP until it successfully re-connects.  This is done with virtually no impact to the users existing work.

If all IP's are unreachable, the application re-does its discovery process (ie does it's initial DNS lookup again) and signs into one of the new IP's (assuming gdnsd is handing out working IP addresses from the other DC).  The recovery/re-connection in this case is visible to the user with a short outage during the discovery/authentication process.

All of this works quite well in most cases however if we are doing any sort of maintenance on one or more servers in either DC, gdnsd only returns the subset of available IP's which means that users who signed in during the maintenance period have a much smaller list of "candidates" to connect to...so then subsequent maintenance on the remaining services in that DC actually causes a user visible outage to despite the system being technically fully available.

Sorry for the long winded description, however I thought it important to understand the background of what we wanted to do and why.

**Comment by blblack** [comment]
It's an interesting use-case, and I don't think there's any combination of existing configuration parameters that would give what you're looking for.  I can take a stab at adding it as a new resource/addrset level parameter.

**Comment by blblack** [comment]
https://github.com/gdnsd/gdnsd/pull/155 has the feature you need, I think.  Let me know if it looks right, and I'll roll it into the next +feature release.

**Comment by andrewheberle** [comment]
Going by the documentation updates, that looks like it would do exactly what we need.

**Comment by blblack** [comment]
This feature was released with 2.4.0, I just forgot to come back here and clean this up.  Closing now :)
