### ISSUE TITLE
Performance Testing

### ISSUE THREAD

**Issue by louishot** [gdnsd/gdnsd#156]
Hi,Guys

I got some Testing Is this normal?
The QPS based on memory or cpu/IO?

```
1 Core and 1GB RAM (lightsail aws)
[Status]DNS Query Performance Testing Finish
[Result]Quries sent:            1000018
[Result]Quries completed:       999958
[Result]Complete percentage:    99.99

[Result]Elapsed time(s):        20.65000

[Result]Queries Per Second:     34230.02179
```

```
2 Core and 4GB RAM (lightsail aws)

[Status]DNS Query Performance Testing Finish
[Result]Quries sent:            1000018
[Result]Quries completed:       999958
[Result]Complete percentage:    99.99

[Result]Elapsed time(s):        20.65000

[Result]Queries Per Second:     48427.02179
```

**Comment by blblack** [comment]
Those results seem within reason, all unknowns considered.  What program are you using to test with above?

Some general notes on perf and testing:

1) The server doesn't auto-scale for CPUs, `udp_threads` and `tcp_threads` config parameters control this stuff.  For a server host that's mostly only doing authdns, I'd set these at roughly the CPU count.  So for a 2-core test instance, `udp_threads = 2` and `tcp_threads = 2` (or experiment with other values somewhere in that ballpark).

2) Be sure you're building/running with `mmsg` and `urcu` features enabled, as these can have a substantial impact on performance.  The configure script notes these at the bottom, e.g.:
```
========================================================================
| Build Info: v2.3.0-13-gcb768b3-dirty
| Build Features: dev mmsg unwind geoip2 urcu
```

3) If you're testing over loopback (tester+server on same host), be sure to account for the performance of the test program as well, it might use a CPU (or more)and it might become a limiting factor itself.

4) If you're testing over a real network, you may need to tweak how many requests the test program allows to be in-flight on the network to remove latency from the QPS calcuation.  For example, if the real network delay is 1ms and the test program only allows one request to be in-flight at any given time, it will never be able to exceed a theoretical tested maximum of 1K QPS.

5) In the past, it's been atypical for any standard, single-thread, single-socket test program using normal APIs like `sendmsg()` to be able generate more than ~50K QPS of traffic, as you start running into kernel limitations on socket API throughput.  That was roughly true on the server side as well.  The mmsg APIs and multi-socket/thread design help scale this out a bit, and the Linux kernel has been improving in general on these fronts over the past couple of years.  I'm not sure what the theoretical maximums are anymore; it's been a while since I've perf tested that deeply.

**Comment by holinhot** [comment]
hardware:
Intel(R) Xeon(R) CPU D-1531 @ 2.20GHz
16GB RAM
7200 RPM HDD

same Adjust udp_threads No effect

There is a very low cpu usage <10%

```
options => {
  listen => {0.0.0.0 => {udp_threads = 1}}
  chaos_response => "unknow"
}

```
```

DNS Query Performance Testing Tool
Version: $Id: queryperf.c,v 1.12 2007/09/05 07:36:04 marka Exp $

[Status] Processing input data
[Status] Sending queries (beginning with 127.0.0.1)
[Status] Testing complete

Statistics:

  Parse input file:     once
  Ended due to:         reaching end of file

  Queries sent:         1000000 queries
  Queries completed:    1000000 queries
  Queries lost:         0 queries
  Queries delayed(?):   0 queries

  RTT max:              0.000233 sec
  RTT min:              0.000009 sec
  RTT average:          0.000044 sec
  RTT std deviation:    0.000009 sec
  RTT out of range:     0 queries

  Percentage completed: 100.00%
  Percentage lost:        0.00%

  Started at:           Sat Mar 10 20:19:47 2018
  Finished at:          Sat Mar 10 20:19:52 2018
  Ran for:              4.476125 seconds

  Queries per second:   223407.523248 qps

```


```
options => {
  listen => {0.0.0.0 => {udp_threads = 12}}
  chaos_response => "unknow"
}
```


```
DNS Query Performance Testing Tool
Version: $Id: queryperf.c,v 1.12 2007/09/05 07:36:04 marka Exp $

[Status] Processing input data
[Status] Sending queries (beginning with 127.0.0.1)
[Status] Testing complete

Statistics:

  Parse input file:     once
  Ended due to:         reaching end of file

  Queries sent:         1000000 queries
  Queries completed:    1000000 queries
  Queries lost:         0 queries
  Queries delayed(?):   0 queries

  RTT max:              0.000232 sec
  RTT min:              0.000018 sec
  RTT average:          0.000044 sec
  RTT std deviation:    0.000009 sec
  RTT out of range:     0 queries

  Percentage completed: 100.00%
  Percentage lost:        0.00%

  Started at:           Sat Mar 10 20:22:12 2018
  Finished at:          Sat Mar 10 20:22:16 2018
  Ran for:              4.491801 seconds

  Queries per second:   222627.850165 qps

```

**Comment by blblack** [comment]
I'm not sure, but I suspect your `queryperf` is single-threaded (but probably allows multiple packets in flight), and so the test tool itself could be a limiting factor.  Have you tried spinning up more than one instance of queryperf in parallel and measuring their aggregate throughput?  Preferably on a remote multi-cpu server over ethernet, I'd think.

Eventually you'll max out a CPU core or start hitting basic limitations that are best solved with OS-level tuning, e.g. RSS multi-queue features of NICs as in https://www.kernel.org/doc/Documentation/networking/scaling.txt .  Even with gdnsd simply configured as one thread per available CPU core, RSS/RPS would help.

Currently gdnsd 2.x lacks a few features that can help take that sort of fine-tuning to the next level, which I hope to put in for 3.x: cpu-pinning of threads, and localizing traffic to the CPU using `SO_INCOMING_CPU` or `SO_ATTACH_REUSEPORT_EBPF` sorts of techniques.

**Comment by blblack** [comment]
The master branch's [docs/Manual.md](https://github.com/gdnsd/gdnsd/blob/master/docs/Manual.md#performance) has some minor updates, which I may expand on a little later with more-realistic testing.  TL;DR is on my reasonably-fast laptop in single-threaded mode over the loopback, gdnsd reaches CPU limitations at ~450K reqs/sec for UDP.

**Comment by louishot** [comment]
Just an update, I tried multiple processes queryperf with CPU E5-2630L v2(24 cores ) 
```
#!/bin/bash
dns_server=$1
testdata=$2
total_runner=$3
rm -rf queryperf_tmp.txt
for i in $(seq 1 $total_runner); do
  {
    queryperf -d $testdata -s $dns_server | grep 'Queries per second:' >> queryperf_tmp.txt
  }&
done
wait
cat queryperf_tmp.txt
rm -rf queryperf_tmp.txt
```
**on the same server**
`./dnstest.sh 127.0.0.1 data.txt 24`
```
  Queries per second:   43440.824700 qps
  Queries per second:   43184.671197 qps
  Queries per second:   43126.237146 qps
  Queries per second:   43039.454914 qps
  Queries per second:   42532.287684 qps
  Queries per second:   42467.223372 qps
  Queries per second:   42270.818107 qps
  Queries per second:   42027.629014 qps
  Queries per second:   42001.610963 qps
  Queries per second:   41940.798717 qps
  Queries per second:   36229.244574 qps
  Queries per second:   34963.990446 qps
  Queries per second:   34487.605200 qps
  Queries per second:   34281.268691 qps
  Queries per second:   34143.949155 qps
  Queries per second:   33980.822732 qps
  Queries per second:   33943.827094 qps
  Queries per second:   33720.210479 qps
  Queries per second:   33568.929480 qps
  Queries per second:   26498.516128 qps
  Queries per second:   24523.500056 qps
  Queries per second:   23944.725536 qps
  Queries per second:   23814.342585 qps
  Queries per second:   23797.349652 qps
  Total: 857929.8376
```


`./dnstest.sh 127.0.0.1 data.txt 10`
```
  Queries per second:   85804.105452 qps
  Queries per second:   78044.221792 qps
  Queries per second:   77504.312766 qps
  Queries per second:   77122.508611 qps
  Queries per second:   73394.024614 qps
  Queries per second:   73385.867928 qps
  Queries per second:   70566.476910 qps
  Queries per second:   70048.086751 qps
  Queries per second:   70043.311842 qps
  Queries per second:   69101.158527 qps
  Total: 745014.0752
```


`./dnstest.sh 127.0.0.1 data.txt 1`
`  Queries per second:   104827.514606 qps`


`from remote client`
```
./dnstest.sh 192.168.1.100 data.txt 24
  Queries per second:   57258.812455 qps
  Queries per second:   56333.574802 qps
  Queries per second:   56102.411946 qps
  Queries per second:   55611.707933 qps
  Queries per second:   55299.739575 qps
  Queries per second:   53711.046601 qps
  Queries per second:   51237.953009 qps
  Queries per second:   49570.724466 qps
  Queries per second:   48442.057414 qps
  Queries per second:   47453.236970 qps
  Queries per second:   44948.881166 qps
  Queries per second:   43799.557283 qps
  Queries per second:   42432.604168 qps
  Queries per second:   42020.762677 qps
  Queries per second:   38856.970909 qps
  Queries per second:   38492.661851 qps
  Queries per second:   38269.384643 qps
  Queries per second:   38200.838310 qps
  Queries per second:   37969.965848 qps
  Queries per second:   36849.344491 qps
  Queries per second:   36810.989747 qps
  Queries per second:   36585.885909 qps
  Queries per second:   35578.226444 qps
  Queries per second:   34750.181398 qps
Total 1076587.52

./dnstest.sh 192.168.1.100 data.txt 12
  Queries per second:   81665.128450 qps
  Queries per second:   79319.017678 qps
  Queries per second:   78670.457932 qps
  Queries per second:   76697.708377 qps
  Queries per second:   73925.882797 qps
  Queries per second:   68729.419834 qps
  Queries per second:   68227.247605 qps
  Queries per second:   66928.758794 qps
  Queries per second:   66120.723720 qps
  Queries per second:   47270.911760 qps
  Queries per second:   46974.076548 qps
  Queries per second:   46346.330593 qps
Total 800875.6641

root@ck3:~# ./dnstest.sh 192.168.1.100 data.txt 1
  Queries per second:   85380.361656 qps
```
