### ISSUE TITLE
any idea support expand-alias?

### ISSUE THREAD

**Issue by holinhot** [gdnsd/gdnsd#157]
https://doc.powerdns.com/authoritative/guides/alias.html

**Comment by blblack** [comment]
It doesn't seem plausible as a simple core feature anytime soon, as it goes against gdnsd's basic design as an authoritative-only server that doesn't block during the req->resp cycle.  Expanding an `ALIAS` RR necessitates the authserver doing client-like lookups against other authservers, possibly in realtime while putting our own client's request on hold.

It could potentially be implemented by a resolver plugin as a method of resolving the existing `DYNA` RRs, but the plugin would have to take care to pre-cache the results, refresh them before expiry in a separate thread in the common case, and have some configurable and/or sane way to deal with various forms of remote failure like no-response, NXDOMAIN, etc (fallback to a static config? Return NOERROR with no answers?).  Pull requests welcome! :)
