### ISSUE TITLE
Per DC statistics

### ISSUE THREAD

**Issue by liviudm** [gdnsd/gdnsd#16]
Hi,

First of all, I want to say that I'm using gdnsd for a month now and it's working excellent. However, I would like to be able to see some detailed statistics. Would it be possible to implement some kind of reporting where one can see the statistics of how many requests made to which defined DC per zone?

**Comment by blblack** [comment]
Way old, but still probably a relevant feature request to look at eventually!

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
