### ISSUE TITLE
failed to start via systemd

### ISSUE THREAD

**Issue by lastsky** [gdnsd/gdnsd#165]
log:

~~~
Jul 23 04:35:04 centos-minimal-vbox systemd[1]: gdnsd.service: main process exited, code=exited, status=42/n/a
Jul 23 04:35:04 centos-minimal-vbox gdnsd[2349]: Loading configuration from '/usr/local/etc/gdnsd/config'
Jul 23 04:35:04 centos-minimal-vbox gdnsd[2349]: open() of pidfile '/usr/local/var/run/gdnsd/gdnsd.pid' failed: Permission denied
Jul 23 04:35:04 centos-minimal-vbox systemd[1]: gdnsd.service: control process exited, code=exited status=42
~~~

systemd file:

~~~
[root@centos-minimal-vbox ~]# cat /etc/systemd/system/gdnsd.service
[Unit]
Description=gdnsd
Documentation=man:gdnsd
After=local-fs.target
After=network.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
NotifyAccess=all
ExecStart=/usr/local/sbin/gdnsd -f start
ExecStop=/usr/local/sbin/gdnsd stop

#---
# Things below this mark are not strictly required for proper operation,
# they're just considered good baseline defaults.
#---

# Usually an authdns server is critical infrastructure; make it
# less likely to be oomkilled if something else goes crazy:
OOMScoreAdjust=-900

# Stricter security environment:
MountFlags=slave
DevicePolicy=closed
PrivateDevices=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
~~~

config:

~~~
[root@centos-minimal-vbox ~]# cat /usr/local/etc/gdnsd/config 
options => {
    username => named
    dns_port => 53
    log_stats => 86400
    tcp_timeout => 15
    listen => [127.0.0.1]
    http_listen => "127.0.0.1"
    tcp_threads => 16 
    udp_threads => 16
    tcp_clients_per_thread => 65535
    zones_strict_data => true
    zones_strict_startup => false
    zones_rfc1035_auto => true
    zones_rfc1035_auto_interval => 10
    zones_rfc1035_quiesce => 1.02
    lock_mem => false
    priority => -6
    chaos_response => gdnsd
}

service_types => {
    my_http_default => { plugin => "http_status" }
}
~~~

permissions are correct!

~~~
[root@centos-minimal-vbox ~]# ls -la /usr/local/var/run/gdnsd/gdnsd.pid
-rw-r----- 1 named named 5 Jul 23 05:31 /usr/local/var/run/gdnsd/gdnsd.pid
[root@centos-minimal-vbox ~]# ls -la /usr/local/var/run/ | grep gdnsd
drwxr-x---  2 named named 22 Jul 23 04:56 gdnsd
~~~

version:

~~~
[root@centos-minimal-vbox ~]# gdnsd
gdnsd version 2.4.0
~~~

can't find anything usefool to understand what happens.

**Comment by lastsky** [comment]
hm. diff for `/etc/systemd/system/gdnsd.service`

~~~diff
-ProtectSystem=full
+#ProtectSystem=full
~~~

than works. a very very very interesting.

**Comment by lastsky** [comment]
fixed in #166 

@blblack ?

**Comment by lastsky** [comment]
from https://www.freedesktop.org/software/systemd/man/systemd.exec.html

> Takes a boolean argument or the special values "full" or "strict". If true, mounts the /usr and /boot directories read-only for processes invoked by this unit. If set to "full", the /etc directory is mounted read-only, too. If set to "strict" the entire file system hierarchy is mounted read-only, except for the API file system subtrees /dev, /proc and /sys (protect these directories using PrivateDevices=, ProtectKernelTunables=, ProtectControlGroups=).

**Comment by blblack** [comment]
I'm glad you found a fix for your issue, and sorry for the very slow responses!  However, I don't think either of the two parts of the proposed patch should be upstream:

The first part about automatic restarts... I've seen this as a workaround for crashy daemons, but this is not a crashy daemon.  If a gdnsd is crashing somewhere in the world, I think we're better off letting it die and having someone file a bug report here.

The latter bit about disabling/downgrading the `ProtectSystem` systemd setting, I think is already sufficiently covered by the comment in the middle of the file noting that:

```
#---
# Things below this mark are not strictly required for proper operation,
# they're just considered good baseline defaults for security and/or perf
#---
```

In general on Linux (where systemd gets used!) I expect most users to use distro packaging into standard paths, and either way there will probably be service file tweaks to make.  I'm going to update that main comment a bit though to make a stronger note that many of these settings will need tweaking with non-system paths, etc.
