### ISSUE TITLE
 plugin_extfile: Service type '_monitor': loading file '/var/tmp/gdnsd/server_status' failed

### ISSUE THREAD

**Issue by louishot** [gdnsd/gdnsd#168]
Hi,

Sep 21 19:42:41 master gdnsd[11995]: rfc1035: Loaded 254 zonefiles from '/etc/gdnsd/zones/'
Sep 21 19:42:41 master gdnsd[11995]: rfc1035: quiescence time is 3 seconds
Sep 21 19:42:41 master gdnsd[11995]: Starting initial round of monitoring ...
Sep 21 19:42:41 master gdnsd[11995]: Cannot open '/var/tmp/gdnsd/server_status' for reading: No such file or directory
Sep 21 19:42:41 master gdnsd[11995]: plugin_extfile: Service type 'jkb_monitor': loading file '/var/tmp/gdnsd/server_status' failed
Sep 21 19:42:41 master gdnsd[11995]: Initial round of monitoring complete
Sep 21 19:42:41 master gdnsd[11995]: admin_state: state file '/var/lib/gdnsd/admin_state' does not yet exist at startup
Sep 21 19:42:41 master gdnsd[11995]: DNS listeners started

root@master:/var/tmp# cat /var/tmp/gdnsd/server_status
192.168.1.100 => DOWN/30
192.168.1.101 => UP/30
192.168.1.102 => DOWN/30

I tried to use debug mode start it working fine

**Comment by blblack** [comment]
Can you specify the version and provide the relevant parts of the config, and how you're starting the non-debug version that fails (systemd unit file or initscript or something?)

**Comment by blblack** [comment]
No followup, nothing to do!

**Comment by Ne00n** [comment]
systemd related I think, using the gdnsd package

**Comment by Ne00n** [comment]
systemctl edit --full gdnsd
TemporaryFileSystem=/tmp/:ro
BindReadOnlyPaths=/tmp/state

Worked for me.
