### ISSUE TITLE
About the root domain support CNAME

### ISSUE THREAD

**Issue by louishot** [gdnsd/gdnsd#169]
Hi,

Right now version cannot support CNAME for the root domain.

I want to build a plugin to support CNAME for the root domain.

Example：

google.com 3600 CNAME www.gg.com

Make a timer every 10s to get ip address of www.gg.com then put in memory
when client ask gdnsd server will answer ip address of www.gg.com

Another method：

there is no timer, when client ask gdnsd, server will to get ip address of www.gg.com then put in memory and set a cache time. answer ip address of www.gg.com. 
This avoids every request need to recursive query www.gg.com 

This looks a lot like cloudflare

I don't have development experience with gdnsd
Any guide please. 
thanks

**Comment by holinhot** [comment]
> What about ANAME which is being actively worked as a standard?
> https://datatracker.ietf.org/doc/draft-ietf-dnsop-aname/

Looks like good. but if the draft get approved still have a long migration cycle

**Comment by blblack** [comment]
If you only want addresses, it's already possible to write such a plugin for gdnsd using DYNA, where the plugin does asynchronous lookups on the remote hostname and caches the result for the core.  For all kinds of reasons, though, I doubt I would add something like this to the core project:

* It's hard to do it safely.
* It's hard to handle all of the possible failure modes in a reasonable way.
* There wouldn't be any transit of edns-client-subnet -level information, so you'd lose geographic optimizations implemented by the target.
* The plugin API (which has never been stable, or well-documented, or abstracted ideally) is due for a massive overhaul and/or removal, which will probably happen during the run up to 4.x.

**Comment by blblack** [comment]
For $reasons above, I don't think this fits well into the overall design.

**Comment by louishot** [comment]
> 
> 
> If you only want addresses, it's already possible to write such a plugin for gdnsd using DYNA, where the plugin does asynchronous lookups on the remote hostname and caches the result for the core. For all kinds of reasons, though, I doubt I would add something like this to the core project:
> 
>     * It's hard to do it safely.
> 
>     * It's hard to handle all of the possible failure modes in a reasonable way.
> 
>     * There wouldn't be any transit of edns-client-subnet -level information, so you'd lose geographic optimizations implemented by the target.
> 
>     * The plugin API (which has never been stable, or well-documented, or abstracted ideally) is due for a massive overhaul and/or removal, which will probably happen during the run up to 4.x.

There is no better way, I just use a script to query ip address and write into zone file
