### ISSUE TITLE
configure fails to check for libev and liburcu-cds

### ISSUE THREAD

**Issue by jngk2** [gdnsd/gdnsd#172]
Firstly, is this an issue, or an just a navigable and minor inconvenience?

---

Linux box 4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64 GNU/Linux
```
$ autoreconf -vif 
$ ./configure
$ make

src/chal.h:30:10: fatal error: ev.h: No such file or directory
 #include <ev.h>
          ^~~~~~
./include/gdnsd/mon.h:28:10: fatal error: urcu-qsbr.h: No such file or directory
 #include <urcu-qsbr.h>

```

**Comment by jngk2** [comment]
add libsodium to that list

**Comment by blblack** [comment]
They're documented in the INSTALL file.  Configure only checks for optional things, but there's little point having it check for things which are required, as compilation will fail anyways (see above!).
