### ISSUE TITLE
[FreeBSD] IPv6 queries to IPv6 IP on a loopback (lo1) interface result in EADDRNOTAVAIL

### ISSUE THREAD

**Issue by zi0r** [gdnsd/gdnsd#174]
Running gdnsd 2.4.0 on FreeBSD 11.2-RELEASE, I have the following setup:

 * No jails involved
 * ix0 has an IPv6 IP configured.
 * lo1 has a separate IPv6 IP configured.
 * gdnsd configured to listen => any
 * Static route on upstream router routes packets destined to lo1's IP to the host IP.

UDP queries made to an IP on lo1 results in gdnsd emitting the following error:
`# error: UDP sendmsg() of 115 bytes failed with retval -1 for client [client:ip:he:re:1:2:3:4]:22961: Can't assign requested address`

Additional details:
 * UDP/TCP queries made to the IP on ix0 succeed.
 * TCP queries made to the same IP on lo1 succeed.
 * UDP queries made from the local server to lo1 succeed.
 * TCP/UDP queries made to IPv4 IPs on lo1 succeed.

My current suspicion is that we're setting the source address wrong in the UDP packet we're crafting to send, but only for IPv6 UDP packets.

**Comment by zi0r** [comment]
A proposed fix has been submitted in PR #175.

**Comment by blblack** [comment]
This was released with stable version 2.4.2 today, and was included in the 2.99.9950-beta release from master as well, so it'll be in 3.0.  Thanks!

**Comment by zi0r** [comment]
FreeBSD port updated to 2.4.2: https://www.freshports.org/dns/gdnsd2
