### ISSUE TITLE
IP2Location instead of Maxmind?

### ISSUE THREAD

**Issue by ghub2015** [gdnsd/gdnsd#178]
Hi Brandon, this is a corollary to Issue #161 (https://github.com/gdnsd/gdnsd/issues/161)

There appears to be another free geoip database alternative to Maxmind:

`IP2Location LITE`
`https://lite.ip2location.com/`

Can this be used with gdnsd without modification?

Thank you in advance.

**Comment by tarabanton** [comment]
It's no longer relevant, as GeoLite2 WILL CONTINUE to contain geo coordinates.
My previous expirience says that IP2Location is a lot more slower, mostly because of "strange" internal structure.

**Comment by ghub2015** [comment]
@tarabanton, it would be helpful for all if you documented the source of your claim.

I was able to find [this post by Maxmind in which they state that the Latitude/Longitude will remain in the GeoLite2 Databases.](https://blog.maxmind.com/2018/04/11/we-are-listening-latitude-and-longitude-will-remain-in-geolite2-databases/)

My original question, on whether IP2Location *could* be used, still stands.

Thank you

**Comment by blblack** [comment]
The short answer is no, IP2Location cannot be used with gdnsd today.

It's possible to support it in the future.  We'd need to look at how they encode data, how the library looks, etc, and then if it all looks usable a code patch could be developed (basically re-implement libgdmaps/gdgeoip2.c for this other database format).

As a workaround with the current gdnsd code, you could simply (hah!) re-encode the data you care about from IP2Location into MaxMind's format.  The format itself is open, and they have a Perl library for writing out the binary format at https://metacpan.org/pod/MaxMind::DB::Writer .

**Comment by ghub2015** [comment]
Hi Brandon, thank you.

This is useful and good to know.

(Closing this issue)
