### ISSUE TITLE
To Use ACL file in gdnsd?

### ISSUE THREAD

**Issue by gh-ghost** [gdnsd/gdnsd#181]
Because I need split locations with state level and country level
for example, CA, NY, OR, Canada, Mexico...etc.
so I make an ip acl file from GeoLite2-City-*.csv with Bind ACL and View

If I can use the ip acl file in gdnsd?
or how should I define map with state collection?
(e.g: WA、OR、CA in a set, NY、NJ、MA in a set..)

**Comment by blblack** [comment]
The geoip plugin can do this kind of thing in general (it loads the binary version of the city database, and allows abstract configuration in terms of countries, states, etc): https://github.com/gdnsd/gdnsd/wiki/GdnsdPluginGeoip .  Do you have more-specific questions about how to configure it for a specific use-case?

**Comment by gh-ghost** [comment]
I test it this week, I use this way.

 plugins => {
   geoip => {
     maps => {
       cn_map => {
         geoip2_db => GeoLite2-City.mmdb,
            datacenters => [dc-01, dc-02, dc-03],
            map => {
              NA => {
                US => {
                  CA => [dc-02],
                  OR => [dc-02],
                  ..........
                  default => [dc-01],
 ..................................................................
 }}}}}}}

seems it can work, but must one line with one zone code?
in Bind config, we can include multi zone code in one line.

 view "us_east" {
       match-clients { CA; OR; .....;};

**Comment by blblack** [comment]
Sorry, the configuration format is as it is, and it's unlikely to change until the whole thing is replaced by a future better iteration of the plugin.

Also, your configuration doesn't allow for any failover at all (which might be what you want?).  If you keep the other datacenters in the list, failover is possible, e.g. with a map like:

```
na_map => {
  geoip2_db => GeoLite2-City.mmdb,
  datacenters => [dc-01, dc-02, dc-03],
  map => {
    NA => {
      US => {
        CA => [dc-02, dc-03, dc-01],
        OR => [dc-02, dc-01, dc-03],
      }
    }
    default => [dc-01, dc-02, dc-03], # This would be implicit anyways, the default-default is the "datacenters" list earlier
  }
}
```

... then if dc-01 goes offline, you can have clients from CA move to dc-03 next, while clients from OR move to dc-02 next.  "Goes offline" would mean either via healthchecks, or manually via `admin_state`, e.g.

```
# Tell gdnsd that dc-01 in map na_map is offline:
echo 'geoip/na_map/dc-01 => DOWN' > /var/lib/gdnsd/admin_state
```

**Comment by gh-ghost** [comment]
I tested it, and I can set default =>[dc-xx] in NA and outside NA with different dc.
seems it can do what I want(both U.S and golbal have different dc )
and thank you let me know how to use the admin_state file :)
