### ISSUE TITLE
admin_state not working?

### ISSUE THREAD

**Issue by cstdenis** [gdnsd/gdnsd#183]
What am I doing wrong? Server meiko is getting some traffic for the hostname thumbs even tho it is set as down as admin state. This is a new server and has been set as down in admin state since before I took the rest of its gdnsd config live so it can't be a dns cacheing issue. 

**Config**

```plugins => {
  geoip => {
    maps => {
        myMap => {
            geoip_db => /usr/local/share/GeoIP/GeoLiteCityv6.dat,
            datacenters = [marin, kuroneko, nana, sana, yukino, mirai, hikaru, meiko],
            auto_dc_coords => {
                kuroneko => [xxx,xxx],
                marin => [xxx,xxx],
                nana => [xxx,xxx],
                sana => [xxx,xxx],
                yukino => [xxx,xxx],
                mirai => [xxx,xxx],
                hikaru => [xxx,xxx],
                meiko => [xxx,xxx]
            }
        }
    },
    resources => {
        picture_servers => $include{servers.cfg},
        thumb_servers => $include{servers.cfg},
        avatar_servers => $include{servers.cfg},
        profile_servers => $include{servers.cfg},
        img_servers => $include{servers.cfg},
    }
  }
}
```

**servers.cfg**
```
            service_types => [ webcheck ],
            map => myMap,
            dcmap = {
                hikaru => {
                        addrs_v4 => [x.x.x.x],
                        addrs_v6 => [x:x:x:x],
                },
                kuroneko => {
                        addrs_v4 => [x.x.x.x],
                        addrs_v6 => [x:x:x:x]
                },
                marin => [x.x.x.x],
                nana => {
                        addrs_v4 => [x.x.x.x],
                },
                sana => {
                        addrs_v4 => [x.x.x.x],
                },
                yukino => {
                        addrs_v4 => [x.x.x.x],
                        addrs_v6 => [x:x:x:x]
                },
                mirai => [x.x.x.x],
                meiko => {
                        addrs_v4 => [x.x.x.x],
#                        addrs_v6 => []
                }
            }
```

**Zone File**
```
pictures  900  IN      DYNA    geoip!picture_servers
thumbs    900  IN      DYNA    geoip!thumb_servers
avatars   900  IN      DYNA    geoip!avatar_servers
profiles  900  IN      DYNA    geoip!profile_servers
img       900  IN      DYNA    geoip!img_servers
```

**admin_state**
```
geoip/thumb_servers/meiko => DOWN
```

**Comment by blblack** [comment]
It should work correctly, we rely on similar config patterns here as well, although not mixed with automatic monitoring...

gdnsd also logs everything about the parsing and effects of `admin_state` to syslog at level `info`.  Looking at the syslog output after startup should be informative if there's any real issue there.

**Comment by blblack** [comment]
(also, what version of gdnsd?)

**Comment by cstdenis** [comment]
Version is 2.2.4_2

Startup info about it says
```# info: admin_state: state of 'geoip/thumb_servers/meiko' forced to DOWN/MAX, real state is NA```

And the status interface agrees
```geoip/thumb_servers/meiko,DOWN!,NA```

However the web server log on meiko is clearly showing access to the thumbs virtual host, tho much less access than if it was not marked down. Seems like that IP only occasionally gets served. 


Also note that an admin state of ```*/meiko => DOWN``` does seem to stop all traffic to the server (tho this is not a solution since I want to be able to control individual services).

**Comment by blblack** [comment]
There are a variety of other technical things that could be causing requests to show up at the site (e.g. HTTP/2 connection coalescing, if some of the other resources share the same IPs and have HTTPS SAN lists which overlap...).  Can you find evidence of gdnsd actually serving a DNS-level response that it shouldn't?

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
