### ISSUE TITLE
Questions: How to master/slave cross datacenter?

### ISSUE THREAD

**Issue by mhf-ir** [gdnsd/gdnsd#188]
What's the best practices for create slaves cross data centers?
Unbound / Bind or etc... as recursive slave that accept transfer zone or similar approach?

**Comment by Showfom** [comment]
I use rsync

**Comment by mhf-ir** [comment]
Good, something like https://github.com/syncthing/syncthing will be great, this tools is great but there is no practical and real world usage example:

**Comment by blblack** [comment]
gdnsd doesn't support zone transfers over the DNS protocol, you'll have to use third party tools to sync data, as mentioned in some of the comments above.
