### ISSUE TITLE
PTR for Prefix

### ISSUE THREAD

**Issue by winkmichael** [gdnsd/gdnsd#189]
Hello I am trying to add a PTR record for a prefix reverse dns but can't seem to get this to work.

I want my /22 prefixes to be defined, I've created a record for each /24
1.168.192 PTR ns1.server.com
2.168.192 PTR ns1.server.com
3.168.192 PTR ns1.server.com
4.168.192 PTR ns1.server.com

I can't seem to get the server to respond when I do a lookup

dig -t PTR 192.168.1.in-addr.arpa.

This always fails. Is there a way to define for a /24 prefix for the reverse dns?

Thanks so much for your help and time!

**Comment by Showfom** [comment]
If you wish to set PTR record for `192.0.2.3` to `example.com`

First, add zone file `2.0.192.in-addr.arpa`

Set PTR record

```
3.2.0.192.in-addr.arpa. PTR example.com.
```

or

```
3 PTR example.com.
```

Then test 

```dig PTR 3.2.0.192.in-addr.arpa @localhost```

**Comment by winkmichael** [comment]
Thanks for the reply, much appreciated. I am able to make PTR records for individual IPs without an issue. They work just fine, however when I try to create a PTR for a  /24  that always fails as not authoritative.

**Comment by Showfom** [comment]
What do you mean by creating PTR for a /24?

**Comment by winkmichael** [comment]
Correct, a PTR for an individual IP comes back successful, however when verifying a prefix it fails. (The RFC on the idea https://tools.ietf.org/html/rfc2317)
If I create a PTR for my /24 both RIPE and LacNIC will complain that the reverse PTR for the prefix is not authoritative. https://www.ripe.net/manage-ips-and-asns/db/support/configuring-reverse-dns

I can however successfully do a reverse lookup of individual records, just not the entire prefix.

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
