### ISSUE TITLE
DC-set alias feature request

### ISSUE THREAD

**Issue by TrurlMcByte** [gdnsd/gdnsd#19]
Another idea - add aliases for sets of DC to easy use in map
Simple example:
datacenters => [dc-01, dc-02, dc-03],
aliases => {
  us1 => [dc-01, dc-02, dc-03]
  us2 => [dc-02, dc-01, dc-03]
  non-us => [dc-03, dc-01, dc-02]
}
map => {
      default => non-us
      NA => {
           US => { default => us1, CA => us2 }, 
       }
}

**Comment by blblack** [comment]
Keeping this open as a reminder for the next Future time that all the plugin/DYNA stuff is reworked.

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
