### ISSUE TITLE
Building own mmdb geoip2 database, what actual format does gdnsd assume?

### ISSUE THREAD

**Issue by lucasRolff** [gdnsd/gdnsd#191]
Been using maxmind geoip2 for quite a long time with gdnsd, however I'm trying to combine a few databases to get a bit more accurate data, for this it requires that I create my own mmdb database.

Having created a database that is compatible with the maxmind geoip2 libraries for python, Perl and PHP, I'd think I had got it right.

Sadly, however when I try to use it in gdnsd, I always end up with following error:

```
# error: plugin_geoip: map cheap: Unexpected error fetching GeoIP2City location data (Success (not an error))
# error: plugin_geoip: map 'cheap': (Re-)loading geoip database '/etc/gdnsd/geoip/GeoIP2-Custom.mmdb' failed!
```
Searching the source I find https://github.com/gdnsd/gdnsd/blob/master/libgdmaps/gdgeoip2.c#L287 - however, my C isn't exactly amazing, so I fail to see why it actually fails.

The metadata a given subnet receives is:

```perl
$custom_ranges{$ipaddress} =  {
    city => {
        geoname_id => 4704482,
        names => {
            en => $city,
        },
    },
    continent => {
        code => $continent_iso,
        geoname_id => 6255149,
        names => {
            en => $continent,
        },
    },
    country => {
        geoname_id => 6252001,
        iso_code => $country_iso,
        names => {
            en => $country,
        },
    },
    location => {
        accuracy_radius => 2,
        latitude => $lat,
        longitude => $long,
    },
    postal => {
       code => $postal,
    },
    registered_country => {
       geoname_id => 6252001,
       iso_code => $cc,
       names => {
           en => $country,
       },
    },
}
```

From what I can see, gdnsd largely relies on continent, country, city, lat+long.

e.g. if using the PHP API:

```
country->isoCode: AU
country->name: Australia
country->names['en']: Australia
city->name: Lytton
postal->code: 0000
location->latitude: -27.416669845581
location->longitude: 153.16667175293
traits->network: 223.252.10.0/25
```

Is there any way I can debug gdnsd and see where it actually fails?

**Comment by blblack** [comment]
[sorry for the slow responses, I've been out of the loop a few months!]

If I had to guess from the source and your data above, most likely the issue it's tripping up on is that gdnsd expects the lat/lon data to be of type `MMDB_DATA_TYPE_DOUBLE` (which is what's in the official maxmind data), and for whatever reason your generator creates `MMDB_DATA_TYPE_FLOAT`, which the other general-purpose libraries don't have a problem with.  You might try finding a way to force the double type in the generator?

**Comment by lucasRolff** [comment]
Hi @blblack,

I managed to solve it by writing the code in Perl (using the official example from Maxmind), and everything seems to work as it should!

Thanks for building awesome software 👍
