### ISSUE TITLE
http status and all monitoring plugin threads stop working - gdnsd/2.4.2

### ISSUE THREAD

**Issue by skrussell** [gdnsd/gdnsd#192]
Hi,

I'm not too sure where to begin, but I'll try.

We have recently attempted to migrate a legacy (gdnsd/2.1.0) cluster of three servers (mixed CentOS 6 & 7) to a brand new cluster of four Ubuntu 20.04 servers running the - as distributed by Ubuntu - gdnsd/2.4.2 daemon.

We have a fairly extensive configuration, hosting some 14 domains with approx 180 DYNA/DYNC records based on 43 unique dynamic resources: 18x geoip, 7x mutlifo, 10x simplefo, & 8x weighted. Those 43 dynamic resources utilise 26 different service plug-in definitions: 14x http_status, 7x tcp_connect, and 5x extmon.

You will hopefully understand if I don't post the full configurations here as: a) they're rather large
& b) they're a little sensitive - if it is necessary that they be seen, then I can probably organise something via a private channel.

The configuration has been in production on the older gdnsd/2.1.0 cluster for quite sometime, and we have had no issues with it. Transposing it onto the new 2.4.2 cluster, however, (adjusting only as necessary, settings like migrating to use geoip2 databases) is not working out well. When we first built the new servers and started our testing, everything appeared to be working fine - all of the dynamic checks were working and the servers were answering our DNS queries just fine. They remained operating under test, without serving live traffic, for approximately 2 weeks, and they displayed no issues with regards to the active monitoring, so we finally started to move the live domains across.

As soon as we started introducing live query traffic, after a few hours, we noticed that the http status pages would stop responding. Restarting the daemon gets it working again, and all seems fine again for a while, but it would stop responding again within a couple of hours. The services continue to answer DNS queries, so although it was frustrating to loose the stats access, we persisted. The more domains we migrated, and hence the more live queries that were introduced, the quicker http status page stopped responding. In the end, under the full load of our 14 domains, the gdnsd daemon would stop responding to the http status requests within 2-3 minutes - so this was/is a highly/easily reproducible issue.

In trying to diagnose the issue, something much more worrying was discovered: the active monitoring checks also stop working at the exact same time as the http status page; in fact, when running as a foreground daemon with the "-D" debug parameter, even the debug messages completely stop appearing at the same time. At this point, DNS requests are still being serviced, but the foreground daemon would fail to respond as expected to CTRL+C and ultimately has to be served with a SIGKILL to exit at all.

I'm not sure what more information I can provide, but obviously this is a bit of a show stopping issue - luckily, the DNS answering thread continues working, but we have had to migrate the primary domains back over to our old servers until we can resolve this issue.

The basic configuration is very simple:
```
options => {
  listen => [ main-IPV4-addr, main-IPV6-addr ],
  tcp_timeout => 15,
  log_stats => 86400,
  zones_default_ttl => 600
}
```
and I have tried with the "realtime_stats", as well as tweaking the various timeout/threads options, but so far nothing appears to have made any difference.

Do you have any suggestions, or is there anything I can try to help diagnose the issue?

The four new servers are made up of 2x Digital Ocean and 2x Linode VPS instances, each with 4Gb RAM & 2x cores - just in case that has any bearing on things. I have attempted to strace the processes, but I don't see anything obvious, but I'm not a programmer and due to the highly threaded nature of gdnsd, it is very difficult to trace with so many active checks and incoming requests.

Many thanks in advance.

**Comment by blblack** [comment]
Sorry I haven't been around much these past months looking for things like this.  I don't have any ready answer, and given how old the ticket is I'm not sure if you've already found some answer.

What it sounds like is that the main thread of execution is stalling out and getting stuck somewhere.  The main thread doesn't handle DNS query traffic, but does handle Ctrl+C and the http status output, as well as the gathering of monitoring results and applying them for runtime effect.  However, the execution of the monitoring is in a separate thread, so it's likely the checks are still executing, just their output is effectively going nowhere.

I've taken a cursory look at the diffs from 2.1.0 to 2.4.2, and nothing stands out as an obvious causative bug.  There was a large amount of change just from 2.1.0 to 2.2.0 (and a lot of file renames due to a relayout of the source tree, which makes digging hard), so that's the most-likely place it happened at if there's a new bug.  You could try attaching gdb to the main thread of execution after it has stalled to find out where in the code it's stalling at.

**Comment by skrussell** [comment]
@blblack, thanks for taking the time to respond.

We pressed ahead with rolling our own gdnsd-3.2.2 (and subsequently, 3.2.3) Debian packages (as found here: https://github.com/skrussell/gdnsd/) and so far, we haven't encountered any such issues. Unfortunately, that does mean that we no-longer have the version 2.4+ testing environment(s) or configurations with which to try the gdb debugging approach.

For us, I would say that this ticket can be closed as we now have a suitable workaround.

**Comment by lucasRolff** [comment]
Sorry for reopening this, however, I'm experiencing the same issue both with 2.4.2 and 3.3.0 (Ubuntu 20.04).

You'll find a coredump here from 2.4.2 (the package from ubuntu repos): https://snaps.hcdn.dk/core.19340 

I'm not sure what would be the actual cause :(

- dns queries continue to work
- HTTP status page stops working
- stracing the main PID including forks (`strace -p <gdnsd_pid> -f -s 2000`), I don't even see the `connect()` calls of the monitoring threads appearing after it hangs.

The dump is fairly large, so might take a bit of time to download.
