### ISSUE TITLE
The issue with configuring wildcard subdomains

### ISSUE THREAD

**Issue by djkobraz** [gdnsd/gdnsd#193]
For example, I have the next records:
; A records
bs1    A    88.99.99.1
bs2    A    88.99.99.2
bs3    A    88.99.99.3

; TXT records
`*`    TXT    "test"

For any subdomains, I have a TXT record "test", but for bs1 bs2 and bs3 server return an empty result, and for every record need set a duplicate value. I think that this is a bug because this is another zone type and there can be different rules. For TXT this is very important because there can be universal records for all subdomains.

**Comment by blblack** [comment]
This isn't really a gdnsd issue, this is a general feature of how wildcard records work in the DNS in general.  It's explained somewhat-decently in https://en.wikipedia.org/wiki/Wildcard_DNS_record , but the bottom line is that the wildcard applies only to names which do not exist.  If you create any record of any type for a specific name, then the wildcard will not apply to that name, even for other record types.  The only way to get the result that you want is to copy the records from the wildcard entry to all of the explicitly-defined names as well, e.g.:

```
; A+TXT records for bs1-bs3
bs1 A 88.99.99.1
bs1 TXT "test"
bs2 A 88.99.99.2
bs2 TXT "test"
bs3 A 88.99.99.3
bs3 TXT "test"

; TXT records for all undefined names
* TXT "test"
```

Or, in the likely case that you have many names which are defined and need a common TXT record, it might be simpler to use some kind of templating engine to manage your zonefiles and inject all of them.
