### ISSUE TITLE
Redirecting requests to a specific DNS server

### ISSUE THREAD

**Issue by VyacheslavSemin** [gdnsd/gdnsd#199]
Hello. Thank you for the great software. But I did not find how to implement the forwarders function in it (similar to DNS bind). Is there such a possibility?
Thanks

**Comment by blblack** [comment]
Sorry, gdnsd is an authoritative-only server.  It doesn't have any ability to forward (or recurse) requests towards other servers.  It only answers queries from its own local authoritative data.
