### ISSUE TITLE
Support for ASN databaases in GeoIP mappings

### ISSUE THREAD

**Issue by paravoid** [gdnsd/gdnsd#200]
For certain use cases, it is useful to be able to redirect ASNs, rather than countries/regions, to different sites. For example, if one has a better interconnection with a particular network in a certain data center, or if one wants to blackhole an entire ASN during an attack etc.

MaxMind offers ASN databases, in the same format (MMDB) that map networks to ASNs, so at least some code could be reused for this :) I don't know how easy or complex it would be to hook it up to the gdnsd configuration code, though!

**Comment by blblack** [comment]
In the long run, what gdnsd is doing in-daemon for mapping GeoIP is intended to move outside the daemon to provide more flexibility for things like this.  The idea is we'll just write python (or whatever language) software that parses various GeoIP databases and outputs a network->dcname map that's consumed by gdnsd, which is oblivious to the logic of the selection.  Basically anything that's currently a "plugin" will move outside of the daemon like that, including the monitoring/state concepts, as this allows more-complex external software to do smarter things (like smooth load ramping for "datacenters", etc).  I think I'd rather defer to that, than further extend what's probably soon-to-be-deprecated-then-dead code in the gdnsd core daemon itself.

In the interim, though, it would be possible to do something similar now by processing the GeoIP ASN database outside of gdnsd and mechanically generating "nets" data for use with the current plugin_geoip, too.
