### ISSUE TITLE
load average spikes when doing health checks with extmon

### ISSUE THREAD

**Issue by derrickhayashi** [gdnsd/gdnsd#201]
Hello, I'm running `gdnsd version 3.2.1` and using the `extmon` plugin to do health checks. 

The extmon plugin then calls a simple shell script that in turns calls curl. The reason this approach is used is because the built-in http_status plugin does not support CNAMEs. There is an upper bound for execution time set for curl, using the `-m` flag. This is pegged to 5s, which is 1s less that the timeout configured in gdnsd's service_types. I have about ~100 service_types in total.

On a 16 core CPU w/ HT, every 2 ~ 3 hours, the load average jumps to about 30 for a brief moment before returning to normal, which is usually about 0.2 or so.

According to my monitoring, processes blocked during this time does not increase.

I've tried using `max_proc` to reduce the number of running processes as I thought this might be the issue, but spike still happens, although at shorter intervals and with less intensity. Setting `max_proc => 10` reduces the intensity of the spikes to about a load average of 4, every 30 ~ 60mins. However, this seems to introduce a new problem. With the health checks being more spread out that the reload time for gdnsd takes longer, up to about 10s.

I've also tried timing how long curl takes the execute by using `{time_total}` for curl and logging that, but I find that most of them return well within the timeout window.

If I disable the health checking by setting the service_type to `up`, this problem goes away.

Can I please get any advise into why this is happening and what else should I be looking into?
If it's due to the large number of processes spawned by this method of health checking, why do I get the load average increases only once every 2 ~ 3 hours instead of more consistently, like at configured interval?

My configuration are as follows:
Each `service_types` configuration looks roughly like the following.
```
myservice_check => {
	plugin => extmon,
	interval => 10,
	timeout => 6,
	up_thresh => 2,
	ok_thresh => 2,
	cmd = ["/usr/local/etc/gdnsd/check.sh", "http", "%%ITEM%%", "80", "/index.html", "200", "test.example.com"],
}
```

`check.sh` is a simple script that takes the parameters and then calls call `curl` with the parameters specified
```
resp=$(curl -m 5 -s -o /dev/null -w "%{http_code}" -H "Host: $host_header" $protocol://$domain:$port$path)
[ $resp == $http_code ]
```

**Comment by blblack** [comment]
I'm sorry, this sounds like a frustrating problem to debug!  There's probably a rational root cause that could be found, and I'd guess at something like there being a pause in name resolution results on the host which re-synchronizes a bunch of executions when they all stall on their hostname lookup, defeating the spread created by max_proc.  But really I think, at the heart of it, your configuration is just asking too much of the very simplistic job scheduler baked into plugin_extmon.   I'd suggest for larger configurations like this, that you manage the scheduling and execution of healthchecks outside of the daemon with some better mechanism, and then bring the results in via plugin_extfile.

**Comment by sheepbrew** [comment]
Thank you for looking in this and the hint about name resolution. By pause in name resolution, you mean delays in doing lookups from the local host to the configured nameservers, yeah? I'll look into seeing if there's anything that could have cause it before trying plugin_extfile.

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
