### ISSUE TITLE
gdnsd in docker no syslog output

### ISSUE THREAD

**Issue by louishot** [gdnsd/gdnsd#204]
Hello,

I using gdnsd in docker today I want to check the gdnsd log but no syslog in /var/log/ in docker container.

volumes:
      - /etc/gdnsd/:/etc/gdnsd/
      - /var/log/:/var/log/

on Host 
cat: /var/log/syslog: No such file or directory

in docker I use /sbin/gdnsd -f start does start with -f option the log will not send to syslog?

Thank you

**Comment by blblack** [comment]
If you're using gdnsd-2.x, then `gdnsd -f start` should send messages to syslog (as long as you don't use the `-x` option to disable it).  If this is the situation, then likely something else is preventing `vsyslog()` from working (e.g. a lack of `/dev/log` or something else of that nature specific to however your libc/syslog implements things).

If you're using gdnsd-3.x, then the `-f` option doesn't do anything (should emit a deprecation warning on startup, actually, but maybe you never see this inside of docker.  In any case "foreground" is the default), and you need an explicit `-l` argument to enable syslog: https://github.com/gdnsd/gdnsd/wiki/Gdnsd

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
