### ISSUE TITLE
gdnsd stucks on start for ever, possible limbo

### ISSUE THREAD

**Issue by Ne00n** [gdnsd/gdnsd#206]
Hey,

I recently start using gdnsd, however with bigger files I somehow managed to make gdnsd stuck in a limbo on start.
Basically gdnsd gets up, burns 100% cpu fills up the memory and then stucks there until systemd kills it.
Can even set the timeout to 15 minutes, won't help it.

Usually it loads the configs and then returns to low cpu usage but that's not the case here.
Do you maybe got any suggestion for that?

My current config is about 29MB in size, the nets = networks.conf is about 39MB in size containing about 1 million rows.
I tried the old Debian version but also compiled the current 3.7, same result.

I get no errors on parsing of the config or such.
Any suggestions? If you want I can provide the files on request.

**Comment by Ne00n** [comment]
I nailed it down to the config file, apparently gdnsd is not happy with a lot of resource maps.

**Comment by Ne00n** [comment]
I tried to reproduce it locally and it seems I figured the point when it goes into limbo.
Basically, I took the same nets mapping file, about 1 million rows.

The only thing I did different was, I did incremental increased the amount of datacenters/pops in the config including the resources and the net mapping file.

Everything worked fine with 13 datacenters/pops.
When I bumped it up to 16, it went into a limbo.

So somewhere in-between 14 and 16 seems to be hitting something that breaks it.
I don't know if its the amount of mappings, which is right now about 256 ish or the datacenters.

The reason why I need so many mappings is because gdnsd dosen't support reloading the config file.
So I create the mappings in advance so I can switch in-between while its running and reload the zones.

Any idea?

**Comment by Ne00n** [comment]
The magic number is indeed 13, if I go over 13 datacenters and 13 * 13 maps it goes nuts.

**Comment by Ne00n** [comment]
Example files:

https://raw.githubusercontent.com/Ne00n/gdns-configs/master/config.works (13 datacenters)
https://raw.githubusercontent.com/Ne00n/gdns-configs/master/config.broken (14 datacenters)

**Comment by blblack** [comment]
I would assume it will eventually finish starting in finite time, but I'm not 100% sure.  You're likely seeing some bad (exponential) scaling in the config setup.  I've tried to reproduce on 3.7.0 using `config.broken` and a simplistic one-line `dc.conf`, and it eventually finishes loading in about 46s on my laptop, so the larger nets data is definitely a factor as well.

The data structures used for this stuff were definitely not designed for the scale of this config with ~16K "resources" being used to... map out many datacenter permutations from a script?

Digging into the design assumptions about "few resources" - geoip is a meta-plugin; all of the mappings to raw IPs are actually handled by another plugin which it also has to synthesize sub-resources for in every single case.  Resources are also simply an array which is searched linearly for `strcmp()` matches on the name while building the config.  We could refactor this code to put resources in a hashtable instead, but that would be a fairly invasive change.

It's also possible your scaling problems could diminish by using an explicit set of sub-resources with the `static` plugin as well, which would avoid the auto-creation of many other redundant complex resources, e.g.:

```
plugins => {
  static => {
     1 => 1.1.1.1,
     2 => 2.2.2.2,
     3 => 3.3.3.3,
     # ...
    }
   geoip => {
     undefined_datacenters_ok = true
     maps => {
        prod => {
          datacenters => [1,2,3,4,5,6,7,8,9,10,11,12,13,14],
          nets = dc.conf
        }
     },
     resources => {
        1 => { map => prod, dcmap => { 1 => %static!1 }},
        # ...
        1-2 => { map => prod, dcmap => { 1 => %static!1, 2 => %static!2 }},
        # ...
        
      }
  }
}
```

It's hard to guess at how the config could be refactored without understanding the use-case, though.  Can you give some insight into what you're trying to accomplish?

**Comment by Ne00n** [comment]
Well, as I said before, I can't reload the config while the server is running, because the your decision was, to not support that.
So my issue is, if I route traffic to Node A, and Node A goes down, I need to somehow be able to reroute traffic.

I can't restart the nameserver every time this happens, waste of cpu, resources yada yada ya.
How I wanted to solve this, is by creating every possible map, that could be used, in a specific case.
A Python3 program does that for me.

So I can update the zone file, point the specific record to a different map which excludes that specific Node or Location, POP whatsoever. Which results in that the traffic gets rerouted.

**Comment by blblack** [comment]
There are some layers to unpack here, but to start with: do the existing health/state mechanisms not meet your needs for how to manage what happens when "Node A goes down?".  That's their intended purpose.  If we can get over that hurdle, then you wouldn't have to generate a giant config, and `replace` should complete seamlessly in reasonable time for true configuration (as opposed to to state-change) reloads.

**Comment by Ne00n** [comment]
Well, its a single point of failure plus it does only measures from a single point.
Which makes not an option, its just not reliable enough.

Of course I would like to generate a shorter config but currently just seems not possible.

**Comment by Ne00n** [comment]
I uploaded the dc.conf file here if you wanna take a look: https://github.com/Ne00n/gdns-configs/blob/master/dc.conf
Should match the .broken config

**Comment by blblack** [comment]
> Well, its a single point of failure plus it does only measures from a single point.
> Which makes not an option, its just not reliable enough.
> 
> Of course I would like to generate a shorter config but currently just seems not possible.

If you use the built-in real monitoring, then yes, it's a single-POV monitor (from each gdnsd instance).  I assume you have some kind of more-advanced monitoring in place now (which is driving your zonefile changes when a node goes down?).  There's the `admin_state` file and the `extfile` monitoring plugin (which is just a more-flexible variant of the same thing as the core `admin_state`), which will load your health results from a file on disk.  Basically whatever's tying your real monitoring to zonefile changes now, could instead modify the `admin_state` file or multiple files that `extfile` reads from.

**Comment by blblack** [comment]
FYI - I tried with your provided larger `dc.conf`, and made the changes I recommended above with the `static` plugin references for the IP addresses, and it loaded in about 83 seconds on my laptop with `checkconf`.  Still not ideal, but much more reasonable in the interim!

My version of your main config looks like:
```
plugins => {
  static => {
    1 => 1.1.1.1,
    2 => 2.2.2.2,
    3 => 3.3.3.3,
    4 => 4.4.4.4,
    5 => 5.5.5.5,
    6 => 6.6.6.6,
    7 => 7.7.7.7,
    8 => 8.8.8.8,
    9 => 9.9.9.9,
    10 => 10.10.10.10,
    11 => 11.11.11.11,
    12 => 12.12.12.12,
    13 => 13.13.13.13,
    14 => 14.14.14.14,
  }
  geoip => {
  undefined_datacenters_ok = true
  maps => {
    prod => {
      datacenters => [1,2,3,4,5,6,7,8,9,10,11,12,13,14],
      nets = dc.conf
    }
  },
  resources => {
        1 => {
        map => prod
        dcmap => {1 => %static!1,}}
# ... skipping the middle here ...
        1-2-3-4-5-6-7-8-9-10-11-12-13-14 => {
        map => prod
        dcmap => {1 => %static!1,2 => %static!2,3 => %static!3,4 => %static!4,5 => %static!5,6 => %static!6,7 => %static!7,8 => %static!8,9 => %static!9,10 => %static!10,11 => %static!11,12 => %static!12,13 => %static!13,14 => %static!14,}}
        
    }
}}
```

**Comment by Ne00n** [comment]
Thanks, I check tomorrow.

Well, I use rqlite as database, which uses Raft Consensus Algorithm to make these decisions.
rqlite is aware which nodes are available, I use that information to reroute DNS traffic.

Basically you can fetch curl rqlite:4003/nodes
Which gives you:

```
{
    "1": {
        "api_addr": "http://10.0.251.12:4003",
        "addr": "10.0.251.12:4004",
        "reachable": true,
        "leader": false
    },
    "2": {
        "api_addr": "http://10.0.251.10:4003",
        "addr": "10.0.251.10:4004",
        "reachable": true,
        "leader": false
    },
    "3": {
        "api_addr": "http://10.0.251.4:4003",
        "addr": "10.0.251.4:4004",
        "reachable": true,
        "leader": false
    },
    "4": {
        "api_addr": "http://10.0.251.5:4003",
        "addr": "10.0.251.5:4004",
        "reachable": true,
        "leader": true
    }
}
```
The names would match the dc map etc.
You mentioned a file, can a json call be used?

**Comment by blblack** [comment]
The `extfile` and `admin_state` (whichever you choose) have their own unique syntax which isn't JSON.  However, you could write a short python program to transform that curl output into the necessary form.  For the `admin_state` case, you'd probably to just find the unreachable ones and output lines like:
```
geoip/prod/2 => DOWN
```
where `prod` can be either the map name (affecting all resources which use that map) or the name of a specific geoip resource.

To go the extfile route requires some more complex config changes.  You'd have a single geoip resource with all of the IPs defined, which attaches a `service_type` which references the `extfile` config, etc.  Something more along the lines of:

```
service_types => {
  rql_state => {
    plugin => "extfile",
    file => "/var/tmp/rql_state",
    direct => true,
  }
}
plugins => {
  geoip => {
    undefined_datacenters_ok = true
    maps => {
      prod => {
        datacenters => [1,2,3,4,5,6,7,8,9,10,11,12,13,14],
        nets = dc.conf
      }
    }
    resources => {
      prod => {
        map => prod,
        service_types => rql_state,
        dcmap => {
          1 => 1.1.1.1,
          2 => 2.2.2.2,
          3 => 3.3.3.3,
          4 => 4.4.4.4,
          5 => 5.5.5.5,
          6 => 6.6.6.6,
          7 => 7.7.7.7,
          8 => 8.8.8.8,
          9 => 9.9.9.9,
          10 => 10.10.10.10,
          11 => 11.11.11.11,
          12 => 12.12.12.12,
          13 => 13.13.13.13,
          14 => 14.14.14.14,
        }
      }
    }
  }
}
```

And then have the translator script generate this from your curl output at `/var/tmp/rql_state` (or wherever you choose to put it):
```
1.1.1.1 => DOWN
2.2.2.2 => UP
# ....
```

**Comment by Ne00n** [comment]
Works so far and looks stable.
Yeah the initial boot phase exceeds the default systemd timeout but can be extended.

I don't restart it often anyway and have no reason to, if its running well.
Thanks for the help.

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
