### ISSUE TITLE
multiple dc

### ISSUE THREAD

**Issue by rsidhaarth** [gdnsd/gdnsd#207]
Hi There,

I have created two different variables for two different DCs (AWS and OVH), but have to use the same coordinates as they are from the same location. I am creating two different variables because they are two different providers and also easy to comment out the variable when required as soon it runs out of bandwidth.

But gDNSd is not resolving to the second DC IP at all. I believe it should resolve on RB. Can this issue be resolved?

For a while, I can list the IP of other DC in the same variable and it is working. But it will be helpful if this is addressed.

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
