### ISSUE TITLE
Weighted Plugin Improvements

### ISSUE THREAD

**Issue by rsidhaarth** [gdnsd/gdnsd#209]
Improvements for Weighted Plugin

1) Cannot able to inherit another plugin into weighted plugin.

Example: 

prodcdn => [%simplefo!cdn, 25]

2) Cannot able to monitor resources via two different monitors

Example:

		weighted =>
		{
				cdn =>
				{
                                    	multi = false,
                                       dc01 =>
                                       {
					service_types = monitor_1,
					lb01 = [1.1.1.1, 25]
                                       }
                                      dc02 =>
                                       {
					service_types = monitor_2,
					lb01 = [8.8.8.8, 25]
                                       }
				}
		}

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
