### ISSUE TITLE
GEOIP Improvements

### ISSUE THREAD

**Issue by rsidhaarth** [gdnsd/gdnsd#210]
In dcmap, cannot able to use more than 1 variable when we are inheriting from another plugin.

Example:

dc01 => [1.1.1.1, 2.2.2.2] - It works
dc01 => [%simplefo!dc01, %metafo!dc02] - It doesnt works

**Comment by faicker** [comment]
same problem with static.

**Comment by rsidhaarth** [comment]
also

dc01 => [%weighted!nat_us_la_dc, 1.1.1.1]

doesnt work

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
