### ISSUE TITLE
Is ragel mandatory to compil?

### ISSUE THREAD

**Issue by EmericBr** [gdnsd/gdnsd#214]
In install doc it is written we need ragel to edit and recompile the .rl file. This implicitly means we can compile without installed ragel
command if we don't want to modify the .rl file. isn't it? In practice i'm unable to compile the untarred sources without the ragel command.

* You'll need Ragel 6.x ( http://www.complang.org/ragel/ ) if you want to
  be able to edit and recompile the .rl parser source code for the
  configuration and zonefile languages.

**Comment by anrxc** [comment]
Ragel is mandatory build dependency of 3.8.x, documentation is out of date.

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
