### ISSUE TITLE
Run external program to get result?

### ISSUE THREAD

**Issue by winkmichael** [gdnsd/gdnsd#216]
Thanks for this amazing DNS server.

I've looked over the docs and googled and can't seem to find this one.

Is there a way to have a DNS lookup run an external program to get the result?

E.g.

record1 TXT /opt/program_to_execute
record2 TXT /opt/program2_to_execute

Thanks for your help
Mike

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
