### ISSUE TITLE
How does include_optional_ns affect the cache on resolver?

### ISSUE THREAD

**Issue by louishot** [gdnsd/gdnsd#217]
Hello,

I know include_optional_ns => false (default)
This option will not add nameserver in response AUTHORITY SECTION when querying non-NS type records.
Will this response to the ISP's cache success rate?

x.root-servers.net > x.gtld-servers.net > ns1.mydns.com > myname.com

It seems that dns resolver does not query NS records for myname.com from the nameserver, because it got nameserver from x.gtld-servers.net

Thank you

**Comment by louishot** [comment]
This option gave different results in the cache resolver(BIND)

include_optional_ns => false
```
; glue
myname.com.             172798  NS      ns1.mydns.com.
                        172798  NS      ns2.mydns.com.
                        172798  NS      ns1.mydns.net.
                        172798  NS      ns2.mydns.net.
```

include_optional_ns => true
```
; answer
myname.com.             86396   NS      ns2.mydns.net.
                        86396   NS      ns2.mydns.com.
                        86396   NS      ns1.mydns.net.
                        86396   NS      ns1.mydns.com.
```

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
