### ISSUE TITLE
HTTPS health probing 2022

### ISSUE THREAD

**Issue by n4n0r** [gdnsd/gdnsd#218]
Hi,

I would like to ask if HTTPS health probing is still not on the table ?

Having embedded health checks such as the simple HTTP one as part of the service is extremely valuable, but nowadays most of the remote services are using TLS / HTTPS. 
Using an external check such as a script or using wget or curl is not viable in a lot of scenarios as it would use too much ressources / memory, if you have a reasonable amount of backends and checks.
Using an external service updating a file that gdnsd would check via the external file plugin is not an option neither, as keeping the service footprint light (no shell, no external script or services) is highly appreciated and sometime a requirement of these new generation containerised infrastructures.

Extending or duplicating the current `gdnsd/src/plugins/http_status.c` to add TLS could be an option ?

Thanks and Good day,

Ronan

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
