### ISSUE TITLE
upgrade to 3.5.2-1 from 2.3.0 Zonefile parse error

### ISSUE THREAD

**Issue by louishot** [gdnsd/gdnsd#223]
Hello,

I just upgrade to 3.5.2-1 from 2.3.0 gdnsd can't start and run gdnsd checkconf some zone output error but not all
`error: rfc1035: Zone 2.x.x.in-addr.arpa.: Zonefile parse error at file /etc/gdnsd/zones/2.x.x.in-addr.arpa line 1: General parse error`
I compared the zone file with no error warning and /etc/gdnsd/zones/2.x.x.in-addr.arpa there is no difference
When I copy all content from the error zone file then delete all line in this zone file then paste into the file again it's work well.

I just want to know what happened
How does 3.5.2-1 load zone files differ from 2.3.0?

I'm guessing this has anything to do with newlines, spaces, tabs?

**Comment by louishot** [comment]
When I use `vi -b /etc/gdnsd/zones/2.x.x.in-addr.arpa` 
I see ^M at the end of each line but one zone file with no error warning I don't see  ^M at the end of line
This should mean something different, but strangely these zones don't have any bugs in 2.3.0

**Comment by louishot** [comment]
last update 
may parser have some changes in 3.5.2
Finally I solved the problem by

```
apt install dos2unix -y
cd /etc/gdnsd/zones/
for zone in *; do
    dos2unix $zone
done
```

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
