### ISSUE TITLE
40 TTL limit for DYNA records

### ISSUE THREAD

**Issue by earas** [gdnsd/gdnsd#224]
all other DNS records (such us A record) works without any issue with higher TTL than 40.
But DYNA records always return 40 if config has higher number than 40. 
If config has lower TTL than 40, requests returns exactly the same TTL in config as we expected.
The problem occurs only if TTL is higher than 40 and record type is DYNA

![image](https://user-images.githubusercontent.com/40065755/199664736-182a7147-ad8b-4be0-b397-5d660081e81c.png)

![image](https://user-images.githubusercontent.com/40065755/199665641-5c0aa4a9-4ec5-4b31-aebe-6cac676430a4.png)

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
