### ISSUE TITLE
How to increase performance checkconf action

### ISSUE THREAD

**Issue by huyduong2792000** [gdnsd/gdnsd#225]
I have 100k plugin and checkconf/start/restart action is very slow ~8m
(I think the reason is because gdnsd is not using the full CPUs of the server.)

Checkconf action time:
![image](https://user-images.githubusercontent.com/53988987/200168899-d24ca169-df7f-4f8c-b13f-9c0aa3baa541.png)

My cpu while checkconf running(only use 1 core):
![image](https://user-images.githubusercontent.com/53988987/200168513-ed538582-2ac6-4dc5-8a5a-96d08bc32b76.png)

My disk performance(ssd):
![image](https://user-images.githubusercontent.com/53988987/200168967-37fdf1af-eef1-46ba-84bf-84ffd5f80abd.png)

My plugin content:
![image](https://user-images.githubusercontent.com/53988987/200169110-550e96b4-fddc-4f05-8b7b-832f5efe0e7d.png)

My config:
![image](https://user-images.githubusercontent.com/53988987/200169145-1ffef20a-0553-409f-aefb-2e6e3e9e0143.png)

I want to know is there any way to increase the performance of this action?

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
