### ISSUE TITLE
Checkconf complains about static plugin

### ISSUE THREAD

**Issue by mdziczkowski** [gdnsd/gdnsd#226]
### Test environment

- OS: Ubuntu (all versions since "trusty")

### Message

Hello. After adding a sub-section with the `plugin => static` into the `service_types`, the `gdns checkconf` started to complain about the `static` plugin with the following message:

```
fatal: static plugin requires a 'plugins' stanza
```

with doesn't tell much and I had used the example given in the documentation, customizing it to my server.

Does anyone got any ideas? Thanks

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
