### ISSUE TITLE
Limit number of RRs in large endpoint lists

### ISSUE THREAD

**Issue by danhanks** [gdnsd/gdnsd#227]
Assume a resource definition like this:
```
my_resource => {
    map => my_map
    service_types => my_service_check
    dcmap => {
        dc1 => [x.x.x.x, x.x.x.y, x.x.x.z]
        dc2 => [x.x.x.x, x.x.x.y, ..., x.x.x.z] # Let's say this is a rather long list
    }
}
```
I'm looking for a way to limit responses which yield the dc2 list to a fixed number of addresses. For example, 20 IPs may be configured in the list, but I only ever want any 8 of the 20 to be returned in a given response. This would spread traffic across all these endpoints, but avoid the problem of clients having to retry over TCP when response size is > 512 bytes. Thinking this would be nice to configure this with a flag at the resource level, maybe like this:

```
my_resource => {
    max_answers => 8 # New resource option
    map => my_map
    service_types => my_service_check
    dcmap => {
        dc1 => [x.x.x.x, x.x.x.y, x.x.x.z]
        dc2 => [x.x.x.x, x.x.x.y, ..., x.x.x.z] # Let's say this is a rather long list
    }
}
```
I'm happy to have a crack at this, but could use some guidance as to where best in the code to work on this.

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
