### ISSUE TITLE
Log unknown queries?

### ISSUE THREAD

**Issue by winkmichael** [gdnsd/gdnsd#228]
Hello all,

I'm looking to log invalid queries, I've tried enabling debug mode but it doesn't appear to log queries - invalid or valid.

Is there a way to enable query logging, and if so can it be done per domain?

Thanks so much for your time and help
Mike

**Comment by blblack** [comment]
No, there's no support for logging queries at all.  DNSTAP might be a viable pathway for sampling them, but it requires some significant work (see the partial implementation in #215).  Working on that isn't currently a priority, unfortunately!
