### ISSUE TITLE
Does 3.x no more inotify-service?

### ISSUE THREAD

**Issue by louishot** [gdnsd/gdnsd#233]
Thank you for great product. We were happy with v2. 
Today when I trying upgrade to v3.5 everything just works but when I change some zone record it doesn't work I see in v3 have gdnsdctl reload-zones cmd 

Must executed command manually in v3 for zone data update?

I use rsync to sync zone data to all servers, it doesn't work on servers if running v3, it take effect immediately if servers running v2.

Thank you

**Comment by louishot** [comment]
I see https://github.com/gdnsd/gdnsd/blob/master/VERSION3.md
Zone (re-)loading still scans the zones directory for zonefiles and automatically names zones based on filenames as before
Zonefiles are now only ever reloaded by explicit command, never by filesystem monitoring
Zone reloads are considered synchronous and atomic: there is no mechanism to reload individual zones, and the entire dataset must load successfully or none of it affects the runtime

**Comment by blblack** [comment]
Yes, this was a design change in V3.  The problem with the filesystem-notification triggers were too numerous (race conditions abound with automated operations and multi-zone changes, etc).
