### ISSUE TITLE
ping: Lacking privilege for icmp socket.

### ISSUE THREAD

**Issue by LS3solutions** [gdnsd/gdnsd#234]
Jun 11 00:15:13 ns1 gdnsd[2724]: ping: Lacking privilege for icmp socket.

Running Debian 11.7

not sure what to do with this.

**Comment by blblack** [comment]
I assume this was an "extmon" configuration.  There's not much we can do about it (within reason) at the gdnsd level.  The user that gdnsd is running as (or other aspects of the process/cgroup security) simply aren't allowing the privileged operations of opening an ICMP socket.
