### ISSUE TITLE
Gdnsd daemonize not starting the server

### ISSUE THREAD

**Issue by SivaKesava1** [gdnsd/gdnsd#238]
Hello Team,

I am trying to run Gdnsd in a container to serve as an authoritative server to test it for [RFC compliance](https://github.com/dns-groot/Ferret#bugs-found). I created the following Dockerfile:

```
FROM ubuntu:bionic
RUN apt-get update 
RUN apt-get install -y \
    autoconf \
    automake \
    cpanminus \
    dnsutils \
    gcc \
    git \
    libev-dev \
    libsodium-dev \
    liburcu-dev \
    make \
    ragel \
    vim 
RUN git clone https://github.com/gdnsd/gdnsd.git
RUN cd gdnsd && \
    autoreconf -vif && \
    ./configure && \
    make install
COPY test.zone. /usr/local/etc/gdnsd/zones/
CMD ["/bin/bash", "-c", "while :; do sleep 10; done"]
```

I am able to successfully create the image and spin a container. From inside the container if I run `gdnsd start` the server starts and serves the `test.zone.` file provided. I am able to stop it using `gdnsdctl stop` successfully. However, when I execute `gdnsd daemonize` there is no error printed and the server does not start.  

How to run the server in the daemon mode successfully? Running the server in daemon mode helps to automate the testing process.

Thanks.

**Comment by blblack** [comment]
This is a bug that was introduced in v3.8.1, which broke "daemonize" but not "start".  There will be a fix in v3.8.2 soon, along with a few other minor fixups!
