### ISSUE TITLE
CNAME chains are not followed

### ISSUE THREAD

**Issue by SivaKesava1** [gdnsd/gdnsd#240]
Hi,

I was checking out GDNSD with some test zone files and provided it the following zone file:

|  	|  	|  	|  	|
|-	|-	|-	|-	|
| test.	| 500 | SOA 	| ns1.outside.com. root.example.com. 3 604800 86400 2419200 604800 	|
| test. 	| 500 | NS 	| ns1.outside.com.  	|
|a.test. 	| 500 | A| 1.1.1.1	|
|c.test.	| 500| CNAME 	| a.test.  	|

For the query _<c.test. , A>_, the GDNSD server returns the following response:
```
         "rcode NOERROR",
          "flags QR AA",
          ";QUESTION",
          "c.test. IN A",
          ";ANSWER",
          "c.test. 500 IN CNAME a.test.",
          ";AUTHORITY",
          ";ADDITIONAL"
```

**Expected behavior**
[RFC 1034 3.6.2](https://tools.ietf.org/html/rfc1034#section-3.6.2) does state 'CNAME chains should be followed,' and the server should return all the last three records. Other implementations like BIND, Knot, and PowerDNS return all the records. I looked up the documentation and did not find any reasoning as to why GDNSD does not follow CNAME chains. 

There was a similar issue in YADIFA and they fixed it https://github.com/yadifa/yadifa/issues/10

Best,
Siva

**Comment by SivaKesava1** [comment]
I'm sorry, I missed that. The rationale for your use case also makes sense, but the resolver will be making multiple RTTs to reach a final answer. 
Consider the simple case where the CNAME target is pointing to the same zone, but the name does not exist. You could return the response with `NXDOMAIN`, but with `NOERROR` the resolver has to make another query to figure out that the domain does not exist. This is just an optimization, but if it working as mentioned in the Config documentation, then I guess it is okay.

**Comment by blblack** [comment]
As mentioned above, this (not including zone-local CNAME chain targets in the response) is a design decision we made.  It is legal and does functional correctly in the real world.  Starting in future versions from 4.x, it won't even be configurable to do so, as going down this road led to significant code simplifications and optimizations for future work.

It is an RTT tradeoff, but this can be ameliorated in critical cases by increasing the CNAME's TTL.

Sorry for the late reply!
