### ISSUE TITLE
Implement Response Rate Limiting

### ISSUE THREAD

**Issue by paravoid** [gdnsd/gdnsd#36]
Apparently DDoSes against DNS infrastructure are becoming common now. Other DNS vendors and people in the DNS community are working on a mitigation method to rate limit responses per query source, labeled "Response Rate Limiting" (RRL), which doesn't look like rocket-science but interesting nevertheless.

The spec is here:
http://ss.vix.su/~vixie/isc-tn-2012-1.txt

A few words here:
http://www.redbarn.org/dns/ratelimits

And a mailing list about implementors:
http://lists.redbarn.org/pipermail/ratelimits/

**Comment by blblack** [comment]
See closing comment in #163 .
