### ISSUE TITLE
GeoIP with IPv6

### ISSUE THREAD

**Issue by wanarta** [gdnsd/gdnsd#39]
I just add IPv6 to config but I always got this is error.

```
plugin_multifo: resource geoip_mini_dc_us-01 (direct): address '2607:xxxx:10:4:0:2:yyyy:zzzz' for 'ipv6' is not IPv4
```

I'm using gdnsd version 1.8.1
This is my config at resource:

```
resources => {
  list_dc => {
    map => dchost,
    service_types => www,
    dcmap => {
      us-01 => {
        ipv4 => xx.xx.xx.xx
        ipv6 => 2607:xxxx:10:4:0:2:yyyy:zzzz
      },
      it-01 => {
        ipv4 => zz.zz.zz.zz
      },
    }
```

Tried the config resource like here http://www.gdnsd.net/ as reference.
Any help will be helpful

Thank you

**Comment by allanjude** [comment]
this documentation seems wrong then: https://github.com/gdnsd/gdnsd/wiki/GdnsdPluginGeoip#another-config-example

        dcmap => {
          us-01 => {
            lb01 => 192.0.2.1,
            lb02 => 192.0.2.2,
            lb03 => 192.0.2.3,
            lb01.v6 => 2001:DB8::1,
            lb02.v6 => 2001:DB8::2,
            lb03.v6 => 2001:DB8::3,
          },
