### ISSUE TITLE
Periodic stats output (For such things as cacti plugins)

### ISSUE THREAD

**Issue by yswery** [gdnsd/gdnsd#67]
Not sure if this is already part of issue #66 but would it be possible to have a way to output stats for a period of time instead of accumulative stats (say every 5min or so)?

Reason I would appreciate this is because I want to write a simple cacti monitoring plugin for our gdnsd servers.

**Comment by blblack** [comment]
The stats are now output in JSON format from a control socket, and there's a CLI client which can query them with `gdnsdctl stats`.  They include uptime, but any state-tracking would have to be external.  Note also that so long as you don't actually stop the daemon, but instead use `gdnsdctl replace` for config updates and/or binary version upgrades, the stats persist and carry over, so there's far less issue with rollover and such.
