### ISSUE TITLE
Event logging

### ISSUE THREAD

**Issue by dene14** [gdnsd/gdnsd#75]
Hi Brandon!

In some cases it would be useful to have some per-event logging for extended stats calculation, analysis and incident/problem management.

Surely it may bring performance bottlenecks, but with certain selectivity of logged events written data amounts shouldn't be really high.

The most important events for logging are:
- nxdomain
- refused
- not implemented
- truncated (DNS / EDNS)
- tcp

Additionally, some in-depth analysis of causation between TC bit set UDP responses and TCP requests may shed some light on non-RFC DNS resolvers (currently we have pretty basic monitoring for this based on stats handler).

Log format may vary for each event, for e.g.
refused.log fields:
- datetime
- event id (if there is any of such)
- query source ip (actually response destination, but the same)
- query source port (actually response destination, but the same)
- queried name
- refusal reason

not_implemented.log fields:
- datetime
- event id (if there is any of such)
- query source ip (actually response destination, but the same)
- query source port (actually response destination, but the same)
- queried name
- what's wrong with that query

nxdomain.log fields:
- datetime
- event id (if there is any of such)
- query source ip (actually response destination, but the same)
- query source port (actually response destination, but the same)
- queried name

udp_tc.log / udp_edns_tc.log:
- datetime
- event id (if there is any of such)
- query source ip (actually response destination, but the same)
- query source port (actually response destination, but the same)
- queried name
- expected buffer/response size
- requested buffer size (for udp_edns_tc.log)

tcp.log:
- datetime
- event id (if there is any of such)
- query source ip (actually response destination, but the same)
- query source port (actually response destination, but the same)
- queried name
- buffer/response size
- duration (optional, time between syn and fin/rst packets or any similar events)

client_subnet.log:
- datetime
- event id (if there is any of such)
- query source ip (actually response destination, but the same)
- query source port (actually response destination, but the same)
- queried name
- client subnet

As per data amounts... Our DNS servers do manage 300KKK events daily, particular event stats as follows (per diem):
tcp_reqs = 41KK
edns_tc = 19K
dns_tc = 40KK
notimp = 0.5K
nxdomain = 68KK
refused = 7.5KK

Any comments?

**Comment by ghub2015** [comment]
+1 for logging important DNS-related events.

One of my biggest concerns in actually using gdnsd in "production" is being able to use, for example, fail2ban to help mitigate the inevitable attacks that would occur from publicly exposing the service to "the world."

Being able to use iptables/ipset and/or blackhole routing to throttle bad requests by parsing logs would be very, very useful.

I am definitely up for testing any functionality submitted to address this.

Thank you

**Comment by blblack** [comment]
No updates/progress here.  I'm generally not keen on emitting complex network events per query, as the logging workload/latency may end up being much higher than handling the original UDP requests, but I can see the desire for eventlogging in general, at least for exceptional cases and perhaps with some intelligent output ratelimiting.  Also, again, this could be done by sniffing the wire traffic with a separate tool, and in either case https://tools.ietf.org/html/draft-ietf-dnsop-dns-capture-format-10 may prove relevant here.

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)

[also, in this case, #215 is probably the relevant path forward, or something like it]
