### ISSUE TITLE
Update zone entries from a plugin

### ISSUE THREAD

**Issue by ghost** [gdnsd/gdnsd#77]
Is it currently possible to update zone files entries from within a plugin? 

If not, it would allow for some cool things like managing sub-domains. Lets say, for example, we ran a web hosting company and we would like to be able to add sub-domains to our DNS servers on-the-fly. We could simply change the zone files themselves but this would involve large amounts of protocol stuff and would probably involve using SSH or something in our code. Using a plugin, we could simply open a socket to our backend and listen for "events".

Is it currently possible? If not what would need to be done to implement it?

**Comment by blblack** [comment]
Old / no-progress
