### ISSUE TITLE
Alias record type

### ISSUE THREAD

**Issue by kriegsmanj** [gdnsd/gdnsd#89]
It would be great if support for an 'alias record' could be implemented.

https://support.cloudflare.com/hc/en-us/articles/200169056-CNAME-Flattening-RFC-compliant-support-for-CNAME-at-the-root
https://nsone.net/2014/05/naked-domains-get-sexier-nsones-alias-records/
http://support.dnsimple.com/articles/domain-apex-heroku/
http://powerdns.13854.n7.nabble.com/Please-test-ALIAS-ANAME-apex-record-in-PowerDNS-td10986.html

**Comment by blblack** [comment]
No real updates here, but keeping this open to remind myself of previous thinking when future plugin/DYNx rework happens.

**Comment by archiephan78** [comment]
Hi,
have any update for this ?
Thanks

**Comment by blblack** [comment]
No real updates, no.  There is a plan and some code slowly forming in the background, for a future replacement of the entire plugin system by something more-flexible that moves all that functionality to external software which can handle all RR types, but it's probably still a long way out from a stable release.  This would allow for e.g. writing a python (or other) script which periodically queries 3rd party DNS results and injects them into records of your local zones.

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
