### ISSUE TITLE
Shared data between config and zone

### ISSUE THREAD

**Issue by yswery** [gdnsd/gdnsd#91]
So I am currently using the multifo functionality in gDNSd

my config is something like this:

```
plugins => {
        multifo => {
                www=> {
                        addrs_v4 => {
                                alpha=> 1.1.1.1,
                                bravo => 2.2.2.2,
                               charlie => 3.3.3.3,
                        }
                        addrs_v6 => {
                                alpha=> 1::1
                                bravo => 2::2,
                               charlie => 3::3,
                        }
                }
        }
}
```

now I want to end up with a zone that has the following:

```
alpha IN A 1.1.1.1
alpha IN AAAA 1::1
bravo IN A 2.2.2.2
bravo IN AAAA 2::2
charlie IN A 3.3.3.3
charlie IN AAAA 3::3
```

Is there anyway I can, say, have these records in a single file and include them in the config and somehow loop through in the zone  or would I have to have repeated data in both zone and config

**Comment by blblack** [comment]
Sorry, I failed to notice this ticket earlier, but no, there is no way to do exactly that in the current config/zone syntax.  You could, however, template both with a templating engine to specify the data once.  The geoip and metafo plugins do have a synthetic resource syntax for situations like this (where one can do e.g. `dc1 DYNA geoip!resname/dc1` to create address records that map explicitly to a specific datacenter without the geoip lookup.

It probably wouldn't be too hard to add similar functionality to some of the other plugins to create syntaxes like `alpha DYNA multifo!www/alpha`, so I'll leave this open as a feature req for that.
