### ISSUE TITLE
SSHFP broken support

### ISSUE THREAD

**Issue by sunnybear** [gdnsd/gdnsd#94]
Hello. We are adding SSHFP resource entries, but gdnsd gives an error for valid RR
example:
box	IN	SSHFP	1	2 88D16B8F1911450A25C064670AC33BF1A0006CFD673846813ABB8239D7B242EA

gdnsd 2.2.0: error: rfc1035: Zone ***: Zonefile parse error at line 27: General parse error

Please advise how to add this RR to gdnsd

**Comment by blblack** [comment]
SSHFP has no explicit support. The set of RRs gdnsd supports in its zonefile are documented in the gdnsd.zonefile manpage: https://github.com/gdnsd/gdnsd/wiki/GdnsdZonefile#supported-resource-record-types .

If you're looking for a short-term solution, you'd have to use RFC3597 syntax, which is fairly ugly.

Basically, your SSHFP above would translate as:
```
box IN TYPE44 \# 34 01 02 88D16B8F1911450A25C064670AC33BF1A0006CFD673846813ABB8239D7B242EA
```

Where the `34` is the length of all of the rest of the data in bytes (including the leading 1,2), and the rest of the bytes are encoded as two-digit hex byte values, with any whitespace breaks that make sense for formatting ignored.

We probably should add SSHFP and a few others, but I'll make a new ticket about that that general issue.
