### ISSUE TITLE
TLSA broken support (?)

### ISSUE THREAD

**Issue by sunnybear** [gdnsd/gdnsd#95]
Hello. Adding TLSA entry
_25._tcp.box	TLSA	3 0 1 df782cd4a268dccb9808591020d7c21e01f41470493fb9b180d7a912622b4719

gdnsd 2.2.0: error: rfc1035: Zone ***: Zonefile parse error at line 27: General parse error

Does TLSA require DNSSEC for domain zone?

**Comment by blblack** [comment]
The answer here is pretty much identical to the SSHFP answer here: https://github.com/gdnsd/gdnsd/issues/94

In this case, I believe you'd translate the above as:
```
_25._tcp.box TYPE52 \# 35 03 00 01 df782cd4a268dccb9808591020d7c21e01f41470493fb9b180d7a912622b4719
```
