### ISSUE TITLE
large records + geoip + large datacenters raise gdnsd start extremely slow

### ISSUE THREAD

**Issue by stutiredboy** [gdnsd/gdnsd#98]
MaxMind mmdb has 249 countries, and a create 249 datacenters in gdnsd config,

after i create large records, such as 500, the gdnsd may take more than 5 minutes to start.

i try to create 5000 records, after an hour, i gived up because gdnsd still parse the config/zone file.

Is it possilbe to imporvement this. I reallized that if i drcrease the datacenters, the starting will faster.

**Comment by blblack** [comment]
I really can't parse what the specific issue is easily from your report, but general observations on the shape of it:
1. Creating a datacenter-per-country seems like an artificial hack that's probably done in a better way.  Do you really have a datacenter in every country?
2. gdnsd really isn't designed to handle hundreds of datacenters.  I'm not surprised that various structures/algorithms don't scale well at that level.  I believe there's a hard cap at 254 datacenters in the design actually, which you're just barely under, and I didn't expect any "reasonable" configuration to come close to.  I kinda figured anyone with triple-digit numbers of actual physical sites probably has the resources to write their own implementation :)
3. Hundreds of zonefile records referencing a geoip resource could be a factor as well, especially given the huge datacenter count in the given resource.

**Comment by blblack** [comment]
Can you give a more-concrete example?  Ellipses or whatever for the long lists is fine, but a real example of how the configuration and zone data is structured would be nice.
